/*
 * This file was automatically generated by EvoSuite
 * Fri May 08 18:43:39 GMT 2026
 */

package org.Exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.Exceptions.EmptyPlaylistException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmptyPlaylistException_ESTest extends EmptyPlaylistException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmptyPlaylistException emptyPlaylistException0 = new EmptyPlaylistException((String) null);
      String string0 = emptyPlaylistException0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmptyPlaylistException emptyPlaylistException0 = new EmptyPlaylistException("#V9h}LN5Fi:t1<%-");
      String string0 = emptyPlaylistException0.getMessage();
      assertEquals("#V9h}LN5Fi:t1<%-", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EmptyPlaylistException emptyPlaylistException0 = new EmptyPlaylistException("");
      String string0 = emptyPlaylistException0.getMessage();
      assertEquals("", string0);
  }
}
