/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:40:42 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonNull;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;
import org.spotifumtp37.util.LocalDateTimeAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LocalDateTimeAdapter_ESTest extends LocalDateTimeAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      Class<Long> class0 = Long.TYPE;
      JsonElement jsonElement0 = localDateTimeAdapter0.serialize(localDateTime0, (Type) class0, (JsonSerializationContext) null);
      LocalDateTime localDateTime1 = localDateTimeAdapter0.deserialize(jsonElement0, (Type) null, (JsonDeserializationContext) null);
      assertNotSame(localDateTime1, localDateTime0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      JsonPrimitive jsonPrimitive0 = new JsonPrimitive("");
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.deserialize(jsonPrimitive0, (Type) null, jsonDeserializationContext0);
        fail("Expecting exception: DateTimeParseException");
      
      } catch(DateTimeParseException e) {
         //
         // Text '' could not be parsed at index 0
         //
         verifyException("java.time.format.DateTimeFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      JsonNull jsonNull0 = JsonNull.INSTANCE;
      Class<Character> class0 = Character.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.deserialize(jsonNull0, class0, jsonDeserializationContext0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // JsonNull
         //
         verifyException("com.google.gson.JsonElement", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      Class<Boolean> class0 = Boolean.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.deserialize((JsonElement) null, class0, jsonDeserializationContext0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.LocalDateTimeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      Class<Boolean> class0 = Boolean.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.serialize((LocalDateTime) null, (Type) class0, jsonSerializationContext0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.LocalDateTimeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      JsonArray jsonArray0 = new JsonArray(30);
      Class<Boolean> class0 = Boolean.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.deserialize(jsonArray0, class0, jsonDeserializationContext0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Array must have size 1, but has size 0
         //
         verifyException("com.google.gson.JsonArray", e);
      }
  }
}
