/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:42:33 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.ExplicitSong;
import org.spotifumtp37.model.album.MultimediaSong;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.util.SongTypeAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SongTypeAdapter_ESTest extends SongTypeAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn("bfZBT%VLvfg)YLn:Y").when(multimediaSong0).getArtist();
      doReturn(606).when(multimediaSong0).getDurationInSeconds();
      doReturn("bfZBT%VLvfg)YLn:Y").when(multimediaSong0).getGenre();
      doReturn("bfZBT%VLvfg)YLn:Y").when(multimediaSong0).getLyrics();
      doReturn("bfZBT%VLvfg)YLn:Y").when(multimediaSong0).getMusicalNotes();
      doReturn(" but was ").when(multimediaSong0).getName();
      doReturn("bfZBT%VLvfg)YLn:Y").when(multimediaSong0).getPublisher();
      doReturn(606).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      Class<Long> class0 = Long.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonElement jsonElement0 = songTypeAdapter0.serialize((Song) multimediaSong1, (Type) class0, jsonSerializationContext0);
      Class<Integer> class1 = Integer.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      Song song0 = songTypeAdapter0.deserialize(jsonElement0, class1, jsonDeserializationContext0);
      assertFalse(song0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      Class<Boolean> class0 = Boolean.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        songTypeAdapter0.serialize((Song) multimediaSong0, (Type) class0, jsonSerializationContext0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Attempted to serialize java.lang.Class: org.spotifumtp37.model.album.MultimediaSong. Forgot to register a type adapter?
         // See https://github.com/google/gson/blob/main/Troubleshooting.md#java-lang-class-unsupported
         //
         verifyException("com.google.gson.internal.bind.TypeAdapters$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      Class<Double> class0 = Double.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        songTypeAdapter0.serialize((Song) null, (Type) class0, jsonSerializationContext0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SongTypeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      Class<Float> class0 = Float.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        songTypeAdapter0.deserialize((JsonElement) null, class0, jsonDeserializationContext0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SongTypeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      JsonPrimitive jsonPrimitive0 = new JsonPrimitive("");
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        songTypeAdapter0.deserialize(jsonPrimitive0, (Type) null, jsonDeserializationContext0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Not a JSON Object: \"\"
         //
         verifyException("com.google.gson.JsonElement", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn("").when(multimediaSong0).getArtist();
      doReturn((-1292)).when(multimediaSong0).getDurationInSeconds();
      doReturn("").when(multimediaSong0).getGenre();
      doReturn("").when(multimediaSong0).getLyrics();
      doReturn("").when(multimediaSong0).getMusicalNotes();
      doReturn("").when(multimediaSong0).getName();
      doReturn("").when(multimediaSong0).getPublisher();
      doReturn((-2317)).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      Class<Boolean> class0 = Boolean.TYPE;
      multimediaSong1.setVideoLink("WeuJv6,>sRIE9\"/I%8");
      JsonElement jsonElement0 = songTypeAdapter0.serialize((Song) multimediaSong1, (Type) class0, (JsonSerializationContext) null);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      Song song0 = songTypeAdapter0.deserialize(jsonElement0, class0, jsonDeserializationContext0);
      assertEquals("", song0.getGenre());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      Song song0 = new Song();
      Class<Double> class0 = Double.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize(song0, (Type) class0, jsonSerializationContext0);
      jsonObject0.addProperty("explicit", "");
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      Song song1 = songTypeAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertFalse(song1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn("$|ZQ72M").when(multimediaSong0).getArtist();
      doReturn(1517).when(multimediaSong0).getDurationInSeconds();
      doReturn("I+q{;$#F/").when(multimediaSong0).getGenre();
      doReturn("I+q{;$#F/").when(multimediaSong0).getLyrics();
      doReturn("$|ZQ72M").when(multimediaSong0).getMusicalNotes();
      doReturn("*/").when(multimediaSong0).getName();
      doReturn("I+q{;$#F/").when(multimediaSong0).getPublisher();
      doReturn((-1873)).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      Class<Double> class0 = Double.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) multimediaSong1, (Type) class0, jsonSerializationContext0);
      jsonObject0.addProperty("multimedia", "com.google.gson.internal.Primitives");
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      Song song0 = songTypeAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertFalse(song0.isMultimedia());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      ExplicitSong explicitSong0 = new ExplicitSong((String) null, (String) null, (String) null, (String) null, (String) null, (String) null, 370);
      Class<Long> class0 = Long.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonElement jsonElement0 = songTypeAdapter0.serialize((Song) explicitSong0, (Type) class0, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      Song song0 = songTypeAdapter0.deserialize(jsonElement0, class0, jsonDeserializationContext0);
      assertNull(song0.getPublisher());
  }
}
