/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 12:38:27 GMT 2026
 */

package org.Model.User;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.Model.Plan.PlanPremiumTop;
import org.Model.Playlist.Playlist;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      User user0 = new User("](VT~c20Gz!3", "](VT~c20Gz!3", "](VT~c20Gz!3", "](VT~c20Gz!3");
      LocalDate localDate0 = MockLocalDate.now();
      int int0 = user0.getMusicReproductionsCount((LocalDate) null, localDate0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("5", "&u}r%x`T^@d", (List<Music>) null);
      linkedList0.add(playlist0);
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("/HF_BlCYZ", "useTypeHashConstant", "S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", "#HI!-", planPremiumBase0, linkedList0, linkedList1);
      Music music0 = new Music();
      try { 
        user0.removeMusicFromPlaylist(music0, (-1982292595));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1982292595
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      Music music0 = new Music("zoZjg?4&c|", "^r", "&", "&", "dl", "+^z5+\u0004h", "net.jqwik.engine.properties.RegisteredArbitraryResolver", (-1663), false);
      try { 
        user0.addMusicPlaylist((-1663), music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1663
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      User user0 = new User();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      Music music0 = new Music();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      user0.setMusicReproductions(linkedList0);
      assertTrue(linkedList0.contains(musicReproduction0));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      User user0 = new User();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      user0.setPlan(planPremiumTop0);
      boolean boolean0 = user0.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("Utilizadores Free n\u00E3o possuem playlists.", "Utilizadores Free n\u00E3o possuem playlists.", "2-", (String) null, planPremiumBase0, linkedList0, linkedList1);
      String string0 = user0.getUsername();
      assertEquals("Utilizadores Free n\u00E3o possuem playlists.", string0);
      assertEquals("Utilizadores Free n\u00E3o possuem playlists.", user0.getEmail());
      assertEquals("2-", user0.getAdress());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      user0.setPlan(planPremiumTop0);
      user0.addPlaylist("Plano: PremiumTop\n    Pontos: 0");
      Playlist playlist0 = user0.getPlaylistById(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("+uuM", "+uuM", " ", "PRX}xpDnyU", (Plan) null, list0, list1);
      user1.getPlan();
      assertEquals("PRX}xpDnyU", user1.getPassword());
      assertEquals("+uuM", user1.getUsername());
      assertEquals(" ", user1.getAdress());
      assertEquals("+uuM", user1.getEmail());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      User user0 = new User((String) null, "3Q&H6d^)LB&", "3Q&H6d^)LB&", (String) null);
      user0.addPoints();
      Plan plan0 = user0.getPlan();
      assertEquals(5, plan0.getPoints());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      planPremiumBase0.setPoints(Integer.MIN_VALUE);
      User user1 = new User("r|T?IiWbPx&Zr", "r|T?IiWbPx&Zr", "r|T?IiWbPx&Zr", "r|T?IiWbPx&Zr", planPremiumBase0, list0, linkedList0);
      Plan plan0 = user1.getPlan();
      assertTrue(plan0.canChooseWhatToPlay());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      User user0 = new User("", "Utilizadores Free n\u00E3o podem adicionar playlists.", "Utilizadores Free n\u00E3o podem adicionar playlists.", "EHZV0#/)lW^7co<");
      String string0 = user0.getPassword();
      assertEquals("Utilizadores Free n\u00E3o podem adicionar playlists.", user0.getEmail());
      assertEquals("EHZV0#/)lW^7co<", string0);
      assertEquals("Utilizadores Free n\u00E3o podem adicionar playlists.", user0.getAdress());
      assertEquals("", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      User user0 = new User((String) null, (String) null, "%s %s", "q ljy{~D'K");
      String string0 = user0.getEmail();
      assertNull(string0);
      assertEquals("%s %s", user0.getAdress());
      assertEquals("q ljy{~D'K", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      User user0 = new User("@wh4GQ]?Ya$G^nb", "??z'*S", "U5yS:@.~tX*", "U5yS:@.~tX*");
      String string0 = user0.getEmail();
      assertEquals("@wh4GQ]?Ya$G^nb", user0.getUsername());
      assertEquals("U5yS:@.~tX*", user0.getAdress());
      assertEquals("U5yS:@.~tX*", user0.getPassword());
      assertEquals("??z'*S", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("", "", "", "");
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      User user1 = new User((String) null, "", (String) null, "", (Plan) null, linkedList0, list0);
      String string0 = user1.getAdress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      User user0 = new User("%AeI)LG-B{v#zQY5eW", "R/<9dS[W#jU;=U(S", "%AeI)LG-B{v#zQY5eW", "ROs>\u00EDVT_+aP8");
      String string0 = user0.getAdress();
      assertEquals("ROs>\u00EDVT_+aP8", user0.getPassword());
      assertEquals("%AeI)LG-B{v#zQY5eW", string0);
      assertEquals("R/<9dS[W#jU;=U(S", user0.getEmail());
      assertEquals("%AeI)LG-B{v#zQY5eW", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      User user0 = new User("Utilizadores Free n\u00E3o possuem playlists.", (String) null, "", (String) null);
      // Undeclared exception!
      try { 
        user0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      User user0 = new User((String) null, "}Q*1@vfE", "}Q*1@vfE", "}Q*1@vfE");
      // Undeclared exception!
      try { 
        user0.setPlaylists((List<Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("", "");
      linkedList0.push(playlist0);
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "", "", "", planPremiumBase0, linkedList0, linkedList1);
      user0.addPlaylist("");
      // Undeclared exception!
      try { 
        user0.removeMusicFromPlaylist((Music) null, 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("", "", "", "");
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      User user1 = new User((String) null, "", (String) null, "", (Plan) null, linkedList0, list0);
      // Undeclared exception!
      try { 
        user1.namePlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      User user0 = new User();
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "");
      playlist0.setAutor((String) null);
      user0.addPlaylistToLibrary(playlist0);
      // Undeclared exception!
      try { 
        user0.getUserPlaylistCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "6?swzeo^U6C", "", "E&wy$X!(5q)", planPremiumBase0, linkedList0, linkedList1);
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.getPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User("org.mockito.internal.creation.bytebuddy.MockMethodAdvice", "org.mockito.internal.creation.bytebuddy.MockMethodAdvice", "vV\"1J$U", "s`V1\"!4\"<:W0=~/o");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.getPlaylistById(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      User user0 = new User("z(q", "qZo%Z1#n2v", "z(q", "qZo%Z1#n2v");
      Music music0 = new Music();
      user0.addMusicReproduction(music0);
      // Undeclared exception!
      try { 
        user0.getMusicReproductionsCount((LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.chrono.ChronoLocalDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      User user0 = new User();
      User user1 = new User((String) null, (String) null, (String) null, (String) null);
      // Undeclared exception!
      try { 
        user1.equals(user0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      User user0 = new User("@wh4GQ]?Ya$G^nb", "??z'*S", "U5yS:@.~tX*", "U5yS:@.~tX*");
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, (String) null);
      user0.addPlaylistToLibrary(playlist0);
      // Undeclared exception!
      try { 
        user0.changePlaylistAutor(" s");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User();
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      User user0 = new User("org.mockito.internal.creation.bytebuddy.MockMethodAdvice", "org.mockito.internal.creation.bytebuddy.MockMethodAdvice", "vV\"1J$U", "s`V1\"!4\"<:W0=~/o");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPlaylist("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      Music music0 = new Music("E&wy$X!(5q)", "6?swzeo^U6C", "", "6?swzeo^U6C", "", "Lz#C}F3aiehQP,&L<", "", 2, false);
      User user0 = new User("", "6?swzeo^U6C", "", "E&wy$X!(5q)", planPremiumBase0, linkedList0, linkedList1);
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addMusicPlaylist(571, music0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      User user0 = null;
      try {
        user0 = new User((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      User user0 = new User("$NX^8M,},$n. ", "$NX^8M,},$n. ", "$NX^8M,},$n. ", "$NX^8M,},$n. ");
      List<Playlist> list0 = user0.getPlaylists();
      User user1 = null;
      try {
        user1 = new User((String) null, "U", "(%s)", "(%s)", planFree0, list0, (List<MusicReproduction>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      try { 
        user0.addPlaylistToLibrary(playlist0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: 
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "");
      playlist0.setAutor("U5yS:@.~tX*");
      user0.addPlaylistToLibrary(playlist0);
      user0.changePlaylistAutor("&");
      assertEquals("", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("", "");
      linkedList0.push(playlist0);
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "", "", "", planPremiumBase0, linkedList0, linkedList1);
      user0.changePlaylistAutor("\uD83C\uDFB5 [#000]                           | Autor:                \n");
      assertEquals("", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "");
      playlist0.setAutor("U5yS:@.~tX*");
      user0.addPlaylistToLibrary(playlist0);
      int int0 = user0.getUserPlaylistCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "");
      user0.addPlaylistToLibrary(playlist0);
      int int0 = user0.getUserPlaylistCount();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "");
      playlist0.setAutor("U5yS:@.~tX*");
      user0.addPlaylistToLibrary(playlist0);
      Music music0 = new Music("C~9r", "C~9r", "", "Pa", "", "", (String) null, 94, false);
      try { 
        user0.removeMusicFromPlaylist(music0, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode remover m\u00FAsicas.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("", "");
      linkedList0.push(playlist0);
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "", "", "", planPremiumBase0, linkedList0, linkedList1);
      user0.addPlaylist("");
      Playlist playlist1 = user0.getPlaylistById(2);
      assertEquals(2, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("W5JF@s`~=\"07", "W5JF@s`~=\"07");
      linkedList0.add(playlist0);
      User user0 = new User();
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      User user1 = new User("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", planPremiumBase0, linkedList0, list0);
      try { 
        user1.getPlaylistById((-1504));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1504
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      User user0 = new User("%AeI)LG-B{v#zQY5eW", "R/<9dS[W#jU;=U(S", "%AeI)LG-B{v#zQY5eW", "ROs>\u00EDVT_+aP8");
      // Undeclared exception!
      try { 
        user0.getPlaylistById(2);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "dl");
      user0.addPlaylistToLibrary(playlist0);
      Music music0 = new Music("C~9r", "C~9r", "dl", "Pa", "", "dl", (String) null, 94, false);
      try { 
        user0.addMusicPlaylist(0, music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("", "");
      linkedList0.push(playlist0);
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      Music music0 = new Music("", "", "", "", "", "", "", 2, false);
      User user0 = new User("", "", "", "", planPremiumBase0, linkedList0, linkedList1);
      user0.addPlaylist("");
      user0.addMusicPlaylist(2, music0);
      user0.removeMusicFromPlaylist(music0, 2);
      assertEquals("", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.addPlaylist("toString");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("", "");
      linkedList0.push(playlist0);
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "6?swzeo^U6C", "", "E&wy$X!(5q)", planPremiumBase0, linkedList0, linkedList1);
      String string0 = user0.namePlaylists();
      assertEquals("6?swzeo^U6C", user0.getEmail());
      assertEquals("\uD83C\uDFB5 [#000]                           | Autor:                \n", string0);
      assertEquals("E&wy$X!(5q)", user0.getPassword());
      assertEquals("", user0.getUsername());
      assertEquals("", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "6?swzeo^U6C", "", "E&wy$X!(5q)", planPremiumBase0, linkedList0, linkedList1);
      user0.namePlaylists();
      assertEquals("E&wy$X!(5q)", user0.getPassword());
      assertEquals("", user0.getAdress());
      assertEquals("", user0.getUsername());
      assertEquals("6?swzeo^U6C", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.namePlaylists();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o possuem playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user1.setAdress(")");
      boolean boolean0 = user0.equals(user1);
      assertFalse(user1.equals((Object)user0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      User user0 = new User();
      User user1 = new User(user0);
      assertTrue(user1.equals((Object)user0));
      
      user1.setEmail("X'{lUAUTv0");
      boolean boolean0 = user1.equals(user0);
      assertFalse(user1.equals((Object)user0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      User user0 = new User();
      User user1 = new User("R", (String) null, (String) null, (String) null);
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      User user0 = new User();
      User user1 = new User(user0);
      boolean boolean0 = user1.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      User user0 = new User();
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      boolean boolean0 = user0.equals(list0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      User user0 = new User();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      linkedList0.add((MusicReproduction) null);
      // Undeclared exception!
      try { 
        user0.setMusicReproductions(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planPremiumTop0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      linkedList1.add((MusicReproduction) null);
      User user0 = new User("net.jqwik.api.lifecycle.TryExecutionResult$Status", "net.jqwik.api.lifecycle.TryExecutionResult$Status", "UP{b<y,Z4]Q<-*", "QY", planPremiumBase0, linkedList0, linkedList1);
      // Undeclared exception!
      try { 
        user0.getMusicReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist((String) null, "");
      user0.addPlaylistToLibrary(playlist0);
      List<Playlist> list0 = user0.getPlaylists();
      user0.setPlaylists(list0);
      // Undeclared exception!
      try { 
        user0.addPlaylistToLibrary(playlist0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      Music music0 = new Music("E&wy$X!(5q)", "6?swzeo^U6C", "", "6?swzeo^U6C", "", "Lz#C}F3aiehQP,&L<", "", 2, false);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList1.add(musicReproduction0);
      User user0 = new User("", "6?swzeo^U6C", "", "E&wy$X!(5q)", planPremiumBase0, linkedList0, linkedList1);
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      assertEquals("6?swzeo^U6C", user0.getEmail());
      assertEquals("E&wy$X!(5q)", user0.getPassword());
      assertEquals("", user0.getAdress());
      assertEquals("", user0.getUsername());
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      User user0 = new User("", "", "", "");
      String string0 = user0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      User user0 = new User("", "", "", "");
      User user1 = user0.clone();
      assertNotSame(user1, user0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      User user0 = new User((String) null, "}Q*1@vfE", "}Q*1@vfE", "}Q*1@vfE");
      String string0 = user0.toString();
      assertEquals("\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DADOS DO UTILIZADOR \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\n  \uD83D\uDC64 Nome de Utilizador: null\n  \uD83D\uDCE7 Email: }Q*1@vfE\n  \uD83C\uDFE0 Morada: }Q*1@vfE\n  \uD83D\uDD11 Password: \u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\n  \uD83D\uDCCB Plano: Plano: Free\n    Pontos: 0\n\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      User user0 = new User((String) null, (String) null, (String) null, (String) null);
      String string0 = user0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      User user0 = new User((String) null, "}Q*1@vfE", "}Q*1@vfE", "}Q*1@vfE");
      String string0 = user0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.hasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      User user0 = new User();
      Plan plan0 = user0.getPlan();
      assertEquals(0, plan0.getPoints());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      User user0 = new User("", "", "", "");
      String string0 = user0.getAdress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      User user0 = new User();
      user0.setUsername("j");
      assertEquals("j", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "6?swzeo^U6C", "", "E&wy$X!(5q)", planPremiumBase0, linkedList0, linkedList1);
      assertEquals("E&wy$X!(5q)", user0.getPassword());
      
      user0.setPassword("org.mockito.internal.");
      assertEquals("", user0.getAdress());
  }
}
