/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 12:57:54 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album((String) null, ";;Db9bV");
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", (String) null, linkedList0);
      String string0 = album0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Album album0 = new Album("\n", (String) null);
      Music music0 = new Music((String) null, (String) null, "E@", (String) null, "E@", "E@", (String) null, 0, true);
      music0.setReproductions(2496);
      album0.addMusic(music0);
      music0.setName("");
      Music music1 = album0.getMusicByName("");
      assertEquals("E@", music1.getGenre());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Album album0 = new Album("DIRECT_DESCENDANTS", "NgmET!tX-oRF");
      Music music0 = new Music();
      album0.addMusic(music0);
      music0.setReproductions((-1932735280));
      Music music1 = album0.getMusicByName("");
      assertEquals("DIRECT_DESCENDANTS", album0.getName());
      assertEquals("NgmET!tX-oRF", album0.getArtist());
      assertNotNull(music1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album("(%s)", ",^}4v#qU~`j");
      Music music0 = new Music();
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("");
      assertEquals(",^}4v#qU~`j", album0.getArtist());
      assertEquals("(%s)", album0.getName());
      assertNotNull(music1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Music music0 = new Music("net.jqwik.engine.descriptor.PropertyMethodDescriptor", "j(EK'T", "net.jqwik.engine.descriptor.PropertyMethodDescriptor", (String) null, "j(EK'T", "", "", 1742, false);
      music0.setName("net.bytebuddy.description.NamedElement");
      linkedList0.add(music0);
      Album album0 = new Album("net.jqwik.engine.descriptor.PropertyMethodDescriptor", "net.jqwik.engine.descriptor.PropertyMethodDescriptor", linkedList0);
      Music music1 = album0.getMusicByName("net.bytebuddy.description.NamedElement");
      assertTrue(music1.equals((Object)music0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = new Album("\n", (String) null);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album("DIRECT_DESCENDANTS", "NgmET!tX-oRF");
      assertEquals("NgmET!tX-oRF", album0.getArtist());
      
      album0.setArtist("");
      album0.getArtist();
      assertEquals("DIRECT_DESCENDANTS", album0.getName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music("$Dispatcher", "$Dispatcher", "f=8?p", "$Dispatcher", "$Dispatcher", "f=8?p", "f=8?p", (-1046), true);
      // Undeclared exception!
      try { 
        album0.removeMusic(music0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusicByName("s5>WB02[Pm2K");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album("Album: ", "bK[.K+ao%Gtjt]MXGD_", (List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Album album0 = new Album("(%s)", ",^}4v#qU~`j");
      Music music0 = new Music();
      album0.addMusic(music0);
      album0.getMusics();
      assertEquals(",^}4v#qU~`j", album0.getArtist());
      assertEquals("(%s)", album0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album("(%s)", ",^}4v#qU~`j");
      album0.getMusics();
      assertEquals(",^}4v#qU~`j", album0.getArtist());
      assertEquals("(%s)", album0.getName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Album album0 = new Album("(%s)", ",^}4v#qU~`j");
      String string0 = album0.getName();
      assertEquals(",^}4v#qU~`j", album0.getArtist());
      assertEquals("(%s)", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Album album0 = new Album("(%s)", ",^}4v#qU~`j");
      String string0 = album0.getArtist();
      assertEquals("(%s)", album0.getName());
      assertEquals(",^}4v#qU~`j", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", (String) null, linkedList0);
      Album album1 = new Album(album0);
      assertNull(album1.getArtist());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      Music music0 = new Music("q", (String) null, (String) null, (String) null, (String) null, "q", "q", (-51890815), false);
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("r");
      assertNull(music1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      Music music0 = new Music("q", (String) null, (String) null, (String) null, (String) null, "q", "q", (-51890815), false);
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("q");
      assertNull(music1.getLyrics());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      String string0 = album0.toString();
      assertEquals("Album: null\nArtista: null\nM\u00FAsicas:\n", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", (String) null, linkedList0);
      linkedList0.add((Music) null);
      album0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      album0.setName("q");
      assertEquals("q", album0.getName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      Music music0 = new Music("q", (String) null, (String) null, (String) null, (String) null, "q", "q", (-51890815), false);
      album0.addMusic(music0);
      String string0 = album0.toString();
      assertEquals("Album: null\nArtista: null\nM\u00FAsicas:\nNome: q\nInterprete: null\nEditora: null\nLetra: null\nLinhas Musicais: null\nGenero Musical: q\nAlbum: q\nDuracao: -51890815\nReproducoes: 0\nExplicita: Nao\n\n", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = null;
      try {
        album1 = new Album(album0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      album0.removeMusic((Music) null);
      assertNull(album0.getName());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      Album album1 = album0.clone();
      assertNotSame(album0, album1);
  }
}
