/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:33:30 GMT 2026
 */

package org.Exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.Exceptions.NoUsersInDatabaseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoUsersInDatabaseException_ESTest extends NoUsersInDatabaseException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoUsersInDatabaseException noUsersInDatabaseException0 = new NoUsersInDatabaseException("");
      String string0 = noUsersInDatabaseException0.getMessage();
      assertEquals("N\u00E3o existem utilizadores na base de dados.", string0);
  }
}
