/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:09:12 GMT 2026
 */

package org.View;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.Controller.Controller;
import org.Model.SpotifUM;
import org.View.MenuManager;
import org.View.PlaylistMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlaylistMenu_ESTest extends PlaylistMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("$_vc!#!cpJrREO^(");
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.show();
          assertTrue(playlistMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          SystemInUtil.addInputLine("Uz?B[[J");
          playlistMenu0.handleInput();
          assertTrue(playlistMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          PlaylistMenu playlistMenu0 = new PlaylistMenu((Controller) null, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.show();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("{ ,Y8!");
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.setPlaylistAsPublic();
            fail("Expecting exception: InputMismatchException");
          
          } catch(InputMismatchException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          PlaylistMenu playlistMenu0 = new PlaylistMenu((Controller) null, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.setPlaylistAsPublic();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.PlaylistMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.setPlaylistAsPublic();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          SystemInUtil.addInputLine("Uz?B[[J");
          // Undeclared exception!
          try { 
            playlistMenu0.removeMusicFromPlaylist();
            fail("Expecting exception: InputMismatchException");
          
          } catch(InputMismatchException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          PlaylistMenu playlistMenu0 = new PlaylistMenu((Controller) null, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.removeMusicFromPlaylist();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.PlaylistMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.removeMusicFromPlaylist();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller((SpotifUM) null);
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.handleInput();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.handleInput();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("Uuj/");
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          SystemInUtil.addInputLine("Uz?B[[J");
          SystemInUtil.addInputLine("\u274C Erro ao obter o artista mais reproduzido: N\u00E3o existem artistas na base de dados.");
          // Undeclared exception!
          try { 
            playlistMenu0.createGenrePlaylist();
            fail("Expecting exception: InputMismatchException");
          
          } catch(InputMismatchException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          PlaylistMenu playlistMenu0 = new PlaylistMenu((Controller) null, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.createGenrePlaylist();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.PlaylistMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.createGenrePlaylist();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("4b8XT:.N");
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.addPublicPlaylistToLibrary();
            fail("Expecting exception: InputMismatchException");
          
          } catch(InputMismatchException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          PlaylistMenu playlistMenu0 = new PlaylistMenu((Controller) null, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.addPublicPlaylistToLibrary();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.PlaylistMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.addPublicPlaylistToLibrary();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SystemInUtil.addInputLine("Uz?B[[J");
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.addMusicToPlaylist();
            fail("Expecting exception: InputMismatchException");
          
          } catch(InputMismatchException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          PlaylistMenu playlistMenu0 = new PlaylistMenu((Controller) null, (MenuManager) null);
          // Undeclared exception!
          try { 
            playlistMenu0.addMusicToPlaylist();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.PlaylistMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          playlistMenu0.closeScanner();
          // Undeclared exception!
          try { 
            playlistMenu0.addMusicToPlaylist();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.removeMusicFromPlaylist();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.createGenrePlaylist();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.addPublicPlaylistToLibrary();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.setPlaylistAsPublic();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.show();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          PlaylistMenu playlistMenu0 = new PlaylistMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            playlistMenu0.addMusicToPlaylist();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
