/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:24:32 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistRandom;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlaylistRandom_ESTest extends PlaylistRandom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom("-[9nbs3ZS]T0&j0", (List<Music>) null);
      List<Music> list0 = playlistRandom0.getMusics();
      Playlist playlist0 = new Playlist("-[9nbs3ZS]T0&j0", "-[9nbs3ZS]T0&j0", list0);
      PlaylistRandom playlistRandom1 = new PlaylistRandom(playlist0);
      PlaylistRandom playlistRandom2 = playlistRandom1.clone();
      assertEquals("-[9nbs3ZS]T0&j0", playlistRandom2.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom("B", linkedList0);
      playlistRandom0.setId((-1617));
      PlaylistRandom playlistRandom1 = playlistRandom0.clone();
      assertEquals("B", playlistRandom1.getName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom("-[9nbs3ZS]T0&j0", (List<Music>) null);
      playlistRandom0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlistRandom0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      PlaylistRandom playlistRandom1 = playlistRandom0.clone();
      playlistRandom0.setAutor((String) null);
      // Undeclared exception!
      try { 
        playlistRandom0.equals(playlistRandom1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlaylistRandom playlistRandom0 = null;
      try {
        playlistRandom0 = new PlaylistRandom((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      PlaylistRandom playlistRandom1 = new PlaylistRandom(playlistRandom0);
      boolean boolean0 = playlistRandom0.equals(playlistRandom1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom("-[9nbs3ZS]T0&j0", (List<Music>) null);
      boolean boolean0 = playlistRandom0.equals("-[9nbs3ZS]T0&j0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      boolean boolean0 = playlistRandom0.equals(playlistRandom0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom("-[9nbs3ZS]T0&j0", (List<Music>) null);
      String string0 = playlistRandom0.toString();
      assertEquals("Playlist Aleat\u00F3ria{nome='-[9nbs3ZS]T0&j0', autor='SpotifyUM', musicas=[]}", string0);
  }
}
