/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:06:24 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Playlist_ESTest extends Playlist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(2484);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music();
      playlist0.addMusic(music0);
      playlist0.removeMusic(music0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Playlist playlist0 = new Playlist("G0x}gx", "");
      assertEquals("G0x}gx", playlist0.getName());
      
      playlist0.setName((String) null);
      playlist0.getName();
      assertEquals("", playlist0.getAutor());
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Playlist playlist0 = new Playlist("Playlist{", "Playlist{");
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music((String) null, "", "", "mZso'sF6^OX|t", (String) null, "8W[ED& 5@", "zJ,IrXn1N", 0, true);
      music0.play();
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music("P /]%j1X6p+c71 9", "P /]%j1X6p+c71 9", "P /]%j1X6p+c71 9", "P /]%j1X6p+c71 9", "<h=(qeV+oN?n8xrjqq-", "P /]%j1X6p+c71 9", "Ul)t)xrFg3Z\"@Itq'", 905, true);
      music0.setReproductions((-2011));
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music();
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music("nome='", "%IBJOA", "s", "D", "net.jqwik.api.EdgeCasesMode", "nome='", (String) null, (-1073), false);
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Playlist playlist0 = new Playlist("ALL_DESCENDANTS", ":h\"4rd-U");
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist1 = new Playlist("!|gX+0='nVvT@IKz", "!|gX+0='nVvT@IKz", list0);
      int int0 = playlist1.getId();
      assertEquals(1, int0);
      assertEquals(":h\"4rd-U", playlist0.getAutor());
      assertEquals("ALL_DESCENDANTS", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setId((-10));
      int int0 = playlist0.getId();
      assertEquals((-10), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("=%^>9", (String) null, linkedList0);
      String string0 = playlist0.getAutor();
      assertNull(string0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("TyC9>=k", "");
      assertEquals("TyC9>=k", playlist0.getName());
      assertEquals("", playlist0.getAutor());
      
      Playlist playlist1 = new Playlist("TyC9>=k", "h=,t;w$^%!%$pXO}m", linkedList0);
      Playlist playlist2 = playlist1.clone();
      assertEquals(1, playlist2.getId());
      assertEquals("TyC9>=k", playlist2.getName());
      assertEquals("h=,t;w$^%!%$pXO}m", playlist2.getAutor());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Playlist playlist0 = new Playlist("STABLE", "STABLE");
      playlist0.setId((-921));
      playlist0.clone();
      assertEquals((-921), playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      List<Music> list0 = linkedList0.subList(0, 0);
      Playlist playlist0 = new Playlist(".", ".", list0);
      linkedList0.add((Music) null);
      // Undeclared exception!
      try { 
        playlist0.setMusics(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Playlist playlist0 = new Playlist("h", "h");
      // Undeclared exception!
      try { 
        playlist0.setMusics((List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Playlist playlist0 = new Playlist("MW C+=Abc/", "MW C+=Abc/");
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Music music0 = new Music();
      linkedList0.add(music0);
      playlist0.setMusics(linkedList0);
      try { 
        playlist0.addMusic(music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: 
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Playlist playlist0 = null;
      try {
        playlist0 = new Playlist((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      int int0 = playlist0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex((-10));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setAutor("hw9Mgo1");
      Playlist playlist1 = new Playlist();
      boolean boolean0 = playlist0.equals(playlist1);
      assertEquals(1, playlist1.getId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Playlist playlist0 = new Playlist("njO)%Ps_L^5", "njO)%Ps_L^5");
      Playlist playlist1 = new Playlist("|Hv+jPt[ai%", "|Hv+jPt[ai%");
      boolean boolean0 = playlist1.equals(playlist0);
      assertEquals(1, playlist1.getId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist(playlist0);
      boolean boolean0 = playlist1.equals(playlist0);
      assertEquals(0, playlist1.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      boolean boolean0 = playlist0.equals(playlist0);
      assertEquals(0, playlist0.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Object object0 = new Object();
      boolean boolean0 = playlist0.equals(object0);
      assertFalse(boolean0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Music music0 = new Music();
      linkedList0.add(music0);
      Playlist playlist0 = new Playlist("hSN9<u@=1yz[", "hSN9<u@=1yz[", linkedList0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Playlist playlist0 = new Playlist("),bj", "),bj", (List<Music>) null);
      Music music0 = new Music();
      playlist0.addMusic(music0);
      List<Music> list0 = playlist0.getMusics();
      assertTrue(list0.contains(music0));
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(".", ".", linkedList0);
      Music music0 = new Music();
      playlist0.removeMusic(music0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Playlist playlist0 = new Playlist("fjO)%!Ps_L^5", (String) null);
      Playlist playlist1 = new Playlist(playlist0);
      // Undeclared exception!
      try { 
        playlist0.equals(playlist1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.hashCode();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(".", ".", linkedList0);
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(".", ".", linkedList0);
      Playlist playlist1 = playlist0.clone();
      assertEquals(0, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(".", ".", linkedList0);
      String string0 = playlist0.toString();
      assertEquals(0, playlist0.getId());
      assertEquals("Playlist{nome='.', autor='.', musicas=[]}", string0);
  }
}
