/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:16:35 GMT 2026
 */

package org.View;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.ProtocolFamily;
import java.net.StandardProtocolFamily;
import java.nio.channels.DatagramChannel;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.SocketChannel;
import java.util.HashMap;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.regex.Pattern;
import org.Controller.Controller;
import org.Model.Playlist.Playlist;
import org.Model.SpotifUM;
import org.View.LoginMenu;
import org.View.MenuManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoginMenu_ESTest extends LoginMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("4");
          SystemInUtil.addInputLine("4");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          loginMenu0.show();
          assertTrue(loginMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("\n\uD83D\uDD10\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u3010 MENU DE LOGIN \u3011\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\uD83D\uDD10\n");
          SystemInUtil.addInputLine("\n\uD83D\uDD10\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u3010 MENU DE LOGIN \u3011\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\uD83D\uDD10\n");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          loginMenu0.register();
          assertTrue(loginMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("");
          SystemInUtil.addInputLine("");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          SystemInUtil.addInputLine("");
          // Undeclared exception!
          try { 
            loginMenu0.register();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SystemInUtil.addInputLine("4");
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          LoginMenu loginMenu0 = new LoginMenu(controller0, menuManager0);
          loginMenu0.handleInput();
          assertTrue(loginMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          MenuManager menuManager0 = new MenuManager((Controller) null);
          LoginMenu loginMenu0 = new LoginMenu((Controller) null, menuManager0);
          SocketChannel socketChannel0 = SocketChannel.open();
          Scanner scanner0 = new Scanner(socketChannel0);
          loginMenu0.setScanner(scanner0);
          // Undeclared exception!
          try { 
            loginMenu0.show();
            fail("Expecting exception: NotYetConnectedException");
          
          } catch(NotYetConnectedException e) {
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          LoginMenu loginMenu0 = new LoginMenu((Controller) null, menuManager0);
          loginMenu0.setScanner((Scanner) null);
          // Undeclared exception!
          try { 
            loginMenu0.show();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.LoginMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          LoginMenu loginMenu0 = new LoginMenu(controller0, menuManager0);
          loginMenu0.closeScanner();
          // Undeclared exception!
          try { 
            loginMenu0.show();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          loginMenu0.setScanner((Scanner) null);
          // Undeclared exception!
          try { 
            loginMenu0.register();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.LoginMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          LoginMenu loginMenu0 = new LoginMenu((Controller) null, menuManager0);
          loginMenu0.closeScanner();
          // Undeclared exception!
          try { 
            loginMenu0.register();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          LoginMenu loginMenu0 = new LoginMenu((Controller) null, (MenuManager) null);
          // Undeclared exception!
          try { 
            loginMenu0.login();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          Controller controller0 = new Controller();
          controller0.addNewUser("", "", "", "");
          SystemInUtil.addInputLine("");
          SystemInUtil.addInputLine("");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          DatagramChannel datagramChannel0 = DatagramChannel.open();
          loginMenu0.closeScanner();
          Scanner scanner0 = new Scanner(datagramChannel0);
          Pattern pattern0 = Pattern.compile("*", (-4614));
          Scanner scanner1 = scanner0.useDelimiter(pattern0);
          loginMenu0.setScanner(scanner1);
          // Undeclared exception!
          try { 
            loginMenu0.login();
            fail("Expecting exception: NotYetConnectedException");
          
          } catch(NotYetConnectedException e) {
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          LoginMenu loginMenu0 = new LoginMenu(controller0, menuManager0);
          loginMenu0.closeScanner();
          // Undeclared exception!
          try { 
            loginMenu0.login();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          SpotifUM spotifUM0 = new SpotifUM();
          spotifUM0.getMusics();
          HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
          spotifUM0.getUsers();
          FileSystemHandling.setPermissions((EvoSuiteFile) null, true, true, true);
          spotifUM0.getAlbums();
          spotifUM0.getArtistReproductions();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          LoginMenu loginMenu0 = new LoginMenu(controller0, menuManager0);
          StandardProtocolFamily standardProtocolFamily0 = StandardProtocolFamily.INET6;
          DatagramChannel datagramChannel0 = DatagramChannel.open((ProtocolFamily) standardProtocolFamily0);
          Scanner scanner0 = new Scanner(datagramChannel0);
          loginMenu0.setScanner(scanner0);
          // Undeclared exception!
          try { 
            loginMenu0.handleInput();
            fail("Expecting exception: NotYetConnectedException");
          
          } catch(NotYetConnectedException e) {
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          LoginMenu loginMenu0 = new LoginMenu((Controller) null, menuManager0);
          loginMenu0.setScanner((Scanner) null);
          // Undeclared exception!
          try { 
            loginMenu0.handleInput();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.LoginMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          LoginMenu loginMenu0 = new LoginMenu(controller0, menuManager0);
          loginMenu0.closeScanner();
          // Undeclared exception!
          try { 
            loginMenu0.handleInput();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("4");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          // Undeclared exception!
          try { 
            loginMenu0.handleInput();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          controller0.addNewUser("e", "e", "e", "e");
          SystemInUtil.addInputLine("e");
          SystemInUtil.addInputLine("e");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          // Undeclared exception!
          try { 
            loginMenu0.login();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.LoginMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("w\"W+");
          SystemInUtil.addInputLine("w\"W+");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          loginMenu0.login();
          assertTrue(loginMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("45");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          loginMenu0.handleInput();
          assertTrue(loginMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          SystemInUtil.addInputLine("4");
          LoginMenu loginMenu0 = new LoginMenu(controller0, (MenuManager) null);
          // Undeclared exception!
          try { 
            loginMenu0.show();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
