/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:19:59 GMT 2026
 */

package org.View;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.SocketChannel;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.Controller.Controller;
import org.Model.SpotifUM;
import org.View.MenuManager;
import org.View.ProfileMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProfileMenu_ESTest extends ProfileMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SystemInUtil.addInputLine("EMI");
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          profileMenu0.show();
          assertTrue(profileMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SystemInUtil.addInputLine("EMI");
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          profileMenu0.handleInput();
          assertTrue(profileMenu0.isRunning());
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          SocketChannel socketChannel0 = SocketChannel.open();
          Scanner scanner0 = new Scanner(socketChannel0);
          profileMenu0.setScanner(scanner0);
          // Undeclared exception!
          try { 
            profileMenu0.show();
            fail("Expecting exception: NotYetConnectedException");
          
          } catch(NotYetConnectedException e) {
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          profileMenu0.setScanner((Scanner) null);
          // Undeclared exception!
          try { 
            profileMenu0.show();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.ProfileMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          profileMenu0.closeScanner();
          // Undeclared exception!
          try { 
            profileMenu0.show();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          ProfileMenu profileMenu0 = new ProfileMenu((Controller) null, menuManager0);
          // Undeclared exception!
          try { 
            profileMenu0.handleInput();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          MenuManager menuManager0 = new MenuManager((Controller) null);
          ProfileMenu profileMenu0 = new ProfileMenu((Controller) null, menuManager0);
          profileMenu0.setScanner((Scanner) null);
          // Undeclared exception!
          try { 
            profileMenu0.handleInput();
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.View.ProfileMenu", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          SpotifUM spotifUM0 = new SpotifUM();
          Controller controller0 = new Controller(spotifUM0);
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          profileMenu0.closeScanner();
          // Undeclared exception!
          try { 
            profileMenu0.handleInput();
            fail("Expecting exception: IllegalStateException");
          
          } catch(IllegalStateException e) {
             //
             // Scanner closed
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          Controller controller0 = new Controller();
          MenuManager menuManager0 = new MenuManager(controller0);
          ProfileMenu profileMenu0 = new ProfileMenu(controller0, menuManager0);
          // Undeclared exception!
          try { 
            profileMenu0.show();
            fail("Expecting exception: NoSuchElementException");
          
          } catch(NoSuchElementException e) {
             //
             // No line found
             //
             verifyException("java.util.Scanner", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
