/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:47:53 GMT 2026
 */

package org.spotifumtp37.model.subscription;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.subscription.PremiumTop;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PremiumTop_ESTest extends PremiumTop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      double double0 = premiumTop0.addPoints(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      double double0 = premiumTop0.addPoints(628.54453);
      assertEquals(644.25814325, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      boolean boolean0 = premiumTop0.canCreatePlaylist();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      boolean boolean0 = premiumTop0.canBrowsePlaylist();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      boolean boolean0 = premiumTop0.canAccessFavouritesList();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      double double0 = premiumTop0.addPoints((-1707.1654044322063));
      assertEquals((-1749.8445395430113), double0, 0.01);
  }
}
