/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:43:11 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.Album;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.model.playlist.Playlist;
import org.spotifumtp37.model.subscription.FreePlan;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.subscription.SubscriptionPlan;
import org.spotifumtp37.model.user.History;
import org.spotifumtp37.model.user.User;
import org.spotifumtp37.util.Stats;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Stats_ESTest extends Stats_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      User user0 = new User();
      HashMap<String, Album> hashMap1 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylistWithinTime(hashMap1, 1);
      Playlist playlist0 = new Playlist(user0, "org.spotifumtp37.util.Stats", "org.spotifumtp37.util.Stats", 1, "org.spotifumtp37.util.Stats", list0);
      hashMap0.put("org.spotifumtp37.util.Stats", playlist0);
      User user1 = Stats.userWithMostPlaylists(hashMap0);
      assertEquals("", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      User user0 = new User();
      Album album0 = new Album();
      List<Song> list0 = album0.getSongs();
      Playlist playlist0 = new Playlist(user0, "DMlj\u0007|r6B_tU:6C/", "", 2932, "DMlj\u0007|r6B_tU:6C/", list0);
      user0.setPontos(464.0);
      hashMap0.put("multimedia=", playlist0);
      User user1 = Stats.userWithMostPlaylists(hashMap0);
      assertEquals(464.0, user1.getPontos(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User((String) null, "org.spotifumtp37.model.subscription.PremiumBase", "org.spotifumtp37.model.subscription.PremiumBase", premiumTop0, "", (-775.352778), linkedList0);
      LinkedList<Song> linkedList1 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "org.spotifumtp37.model.subscription.PremiumBase", "", 2147483645, "", linkedList1);
      hashMap0.put("org.spotifumtp37.model.subscription.PremiumBase", playlist0);
      User user1 = Stats.userWithMostPlaylists(hashMap0);
      assertEquals((-775.352778), user1.getPontos(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      Album album0 = new Album();
      Song song0 = album0.getCurrentSong();
      user0.updateHistory(song0);
      hashMap0.put((String) null, user0);
      String string0 = Stats.mostListenedGenre(hashMap0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put((String) null, user0);
      User user1 = Stats.getUserWithMostPoints(hashMap0);
      assertSame(user1, user0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("^A@k9g=1-N#%nN", user0);
      user0.setPontos(1860.68507);
      User user1 = Stats.getUserWithMostPoints(hashMap0);
      assertEquals("", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      FreePlan freePlan0 = new FreePlan();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("q^qh<", "q^qh<", "", freePlan0, "", (-1.0), linkedList0);
      hashMap0.put("q^qh<", user0);
      User user1 = Stats.getUserWithMostPoints(hashMap0);
      assertEquals("", user1.getPassword());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      User user1 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertEquals("", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      LocalDate localDate0 = MockLocalDate.ofYearDay(2, 2);
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(2);
      PremiumBase premiumBase0 = new PremiumBase();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("org.spotifumtp37.util.Stats", "=i&-:", "=i&-:", premiumBase0, "org.spotifumtp37.util.Stats", 2, linkedList0);
      hashMap0.put("[WF~*+", user0);
      LocalDateTime localDateTime0 = MockLocalDateTime.of(localDate0, localTime0);
      User user1 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertEquals(2.0, user1.getPontos(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("r", "org.spotifumtp37.util.Stats", "(", (SubscriptionPlan) null, "org.spotifumtp37.util.Stats", (-1038.0), list0);
      hashMap0.put("(", user1);
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      User user2 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertEquals((-1038.0), user2.getPontos(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put((String) null, user0);
      User user1 = Stats.getTopListener(hashMap0);
      assertEquals("", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("^A@k9g=1-N#%nN", user0);
      user0.setPontos(1860.68507);
      User user1 = Stats.getTopListener(hashMap0);
      assertEquals("", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      FreePlan freePlan0 = new FreePlan();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("q^qh<", "q^qh<", "", freePlan0, "", (-1.0), linkedList0);
      hashMap0.put("q^qh<", user0);
      User user1 = Stats.getTopListener(hashMap0);
      assertEquals("", user1.getPassword());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Album album0 = new Album();
      album0.addSong("!~5", " bZHCJw`GNN`-y_]A", " bZHCJw`GNN`-y_]A", "!~5", "!~5", 1, false, false, " bZHCJw`GNN`-y_]A");
      hashMap0.put("", album0);
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertEquals("", song0.getArtist());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Album album0 = new Album();
      album0.addSong("7y", "l,", "l,", "", "\"h[[r7]d5s/1n", 2147483645, true, true, "");
      hashMap0.put("", album0);
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertEquals("l,", song0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Album album0 = new Album();
      album0.setArtist("^669GiN!");
      album0.addSong("History{song=", "dG0$*zMg?tw\"#;E%./0", "History{song=", "dG0$*zMg?tw\"#;E%./0", "History{song=", 425, false, false, "History{song=");
      hashMap0.put("History{song=", album0);
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertEquals(1, hashMap0.size());
      assertEquals("^669GiN!", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      hashMap0.put("FJ\u0014L:d\"C\"\"1[", (Playlist) null);
      // Undeclared exception!
      try { 
        Stats.userWithMostPlaylists(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("", (Album) null);
      // Undeclared exception!
      try { 
        Stats.getMostListenedArtist(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      hashMap0.put("", (Playlist) null);
      // Undeclared exception!
      try { 
        Stats.countPublicPlaylists(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$2$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, ", musicalNotes='", "", (-1), "public", linkedList0);
      hashMap0.put("u&/r/$R'c,", playlist0);
      User user0 = Stats.userWithMostPlaylists(hashMap0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      User user0 = Stats.userWithMostPlaylists((Map<String, Playlist>) null);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, ", musicalNotes='", "", (-1), "public", linkedList0);
      hashMap0.put("u&/r/$R'c,", playlist0);
      long long0 = Stats.countPublicPlaylists(hashMap0);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      long long0 = Stats.countPublicPlaylists(hashMap0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      long long0 = Stats.countPublicPlaylists((Map<String, Playlist>) null);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      HashMap<String, Playlist> hashMap1 = new HashMap<String, Playlist>();
      User user0 = Stats.userWithMostPlaylists(hashMap1);
      hashMap0.put((String) null, user0);
      // Undeclared exception!
      try { 
        Stats.mostListenedGenre(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      String string0 = Stats.mostListenedGenre(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String string0 = Stats.mostListenedGenre((Map<String, User>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = Stats.getTopListener(hashMap0);
      hashMap0.put("", user0);
      // Undeclared exception!
      try { 
        Stats.getUserWithMostPoints(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = Stats.getUserWithMostPoints(hashMap0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = Stats.getUserWithMostPoints((Map<String, User>) null);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = Stats.getTopListenerFromDate(hashMap0, (LocalDateTime) null);
      hashMap0.put("org.spotifumtp37.model.album.Song", user0);
      User user1 = Stats.getTopListenerFromDate(hashMap0, (LocalDateTime) null);
      assertNull(user1);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      User user0 = Stats.getTopListenerFromDate((Map<String, User>) null, localDateTime0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      HashMap<String, Playlist> hashMap1 = new HashMap<String, Playlist>();
      User user0 = Stats.userWithMostPlaylists(hashMap1);
      hashMap0.put((String) null, user0);
      // Undeclared exception!
      try { 
        Stats.getTopListener(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = Stats.getTopListener(hashMap0);
      hashMap0.put("", user0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      // Undeclared exception!
      try { 
        Stats.getTopListenerFromDate(hashMap0, localDateTime0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      User user0 = Stats.getTopListener((Map<String, User>) null);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Album album0 = new Album();
      album0.addSong("!~5", " bZHCJw`GNN`-y_]A", " bZHCJw`GNN`-y_]A", "!~5", "!~5", 1, false, false, " bZHCJw`GNN`-y_]A");
      hashMap0.put("", album0);
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Album album0 = new Album();
      hashMap0.put("", album0);
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      String string0 = Stats.getMostListenedArtist((Map<String, Album>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("", (Album) null);
      // Undeclared exception!
      try { 
        Stats.getMostPlayedSong(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertNull(song0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Song song0 = Stats.getMostPlayedSong((Map<String, Album>) null);
      assertNull(song0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Stats stats0 = new Stats();
  }
}
