/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Apr 24 13:05:50 GMT 2026
 */

package org.View;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

@EvoSuiteClassExclude
public class MenuManager_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  protected static ExecutorService executor; 

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.View.MenuManager"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    executor.shutdownNow(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
    org.evosuite.runtime.util.SystemInUtil.getInstance().initForTestCase(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/gongas/Desktop/3ano2sem/ATS_Aulas/ATS/SpotifyUM"); 
    java.lang.System.setProperty("user.home", "/home/gongas"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "gongas"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MenuManager_ESTest_scaffolding.class.getClassLoader() ,
      "org.Exceptions.NoReproductionsInDatabaseException",
      "org.View.ProfileEditorMenu",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "org.Model.SpotifUM",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "net.jqwik.api.lifecycle.PropagationMode",
      "org.Exceptions.EmptyPlaylistException",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "org.View.AdminMenu",
      "org.Model.Playlist.Playlist",
      "org.Model.Plan.Plan",
      "org.View.ReproductionMenu$PlayerAction",
      "org.Controller.dtos.MusicInfo",
      "org.Model.Plan.PlanPremiumTop",
      "net.jqwik.api.EdgeCasesMode",
      "net.bytebuddy.description.TypeVariableSource",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "net.jqwik.api.ShrinkingMode",
      "org.Model.Plan.PlanFree",
      "org.Model.User.User",
      "org.Utils.Serialization",
      "org.Model.Playlist.PlaylistRandom",
      "org.Exceptions.NoPremissionException",
      "net.bytebuddy.description.type.TypeDefinition",
      "org.View.PlaylistCreationMenu",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.Model.Music.Music",
      "net.bytebuddy.description.type.TypeDescription",
      "org.View.ProfileMenu",
      "org.Exceptions.NotFoundException",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.jqwik.api.GenerationMode",
      "org.View.PlanMenu",
      "org.View.MainMenu",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.description.ByteCodeElement",
      "org.Exceptions.NoMusicsInDatabaseException",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "org.Exceptions.AlreadyExistsException",
      "org.View.ReproductionMenu",
      "net.bytebuddy.description.DeclaredByType",
      "org.Model.Album.Album",
      "org.Model.Playlist.PlaylistFavorites",
      "net.bytebuddy.build.Plugin",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.implementation.EqualsMethod",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "org.View.MenuManager",
      "org.Model.Plan.PlanPremiumBase",
      "org.Exceptions.NoArtistsInDatabaseException",
      "org.View.LoginMenu",
      "net.jqwik.api.FixedSeedMode",
      "org.apiguardian.api.API",
      "org.View.PlaylistMenu",
      "org.apiguardian.api.API$Status",
      "net.jqwik.api.AfterFailureMode",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "org.View.Menu",
      "net.bytebuddy.matcher.ElementMatcher",
      "org.View.StatisticsMenu",
      "net.bytebuddy.build.Plugin$Factory",
      "net.bytebuddy.implementation.HashCodeMethod",
      "org.Model.Music.MusicReproduction",
      "org.Controller.Controller",
      "net.bytebuddy.description.NamedElement",
      "org.Model.Music.MusicMultimedia",
      "org.Exceptions.NoUsersInDatabaseException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MenuManager_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.View.MenuManager",
      "org.apiguardian.api.API$Status",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.jqwik.api.EdgeCasesMode",
      "net.jqwik.api.FixedSeedMode",
      "net.jqwik.api.AfterFailureMode",
      "net.jqwik.api.ShrinkingMode",
      "net.jqwik.api.GenerationMode",
      "net.jqwik.api.lifecycle.PropagationMode",
      "org.View.Menu",
      "org.View.LoginMenu",
      "org.Controller.Controller",
      "org.Model.SpotifUM",
      "org.View.ProfileMenu",
      "org.Exceptions.NoArtistsInDatabaseException",
      "org.Model.Music.Music",
      "org.Model.Music.MusicMultimedia",
      "org.Exceptions.NotFoundException",
      "org.View.AdminMenu",
      "org.Utils.Serialization",
      "org.View.ProfileEditorMenu",
      "org.View.PlaylistMenu",
      "org.Model.Plan.Plan",
      "org.Model.Plan.PlanPremiumBase",
      "org.View.ReproductionMenu",
      "org.Exceptions.NoMusicsInDatabaseException",
      "org.Model.Plan.PlanFree",
      "org.Model.Plan.PlanPremiumTop",
      "org.Exceptions.NoUsersInDatabaseException",
      "org.Model.Playlist.Playlist",
      "org.View.PlanMenu",
      "org.View.MainMenu",
      "org.Model.User.User",
      "org.Model.Playlist.PlaylistRandom",
      "org.Controller.dtos.MusicInfo",
      "org.Exceptions.NoReproductionsInDatabaseException",
      "org.View.PlaylistCreationMenu",
      "org.View.StatisticsMenu",
      "org.Model.Album.Album"
    );
  }
}
