/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Apr 24 12:51:45 GMT 2026
 */

package org.View;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

@EvoSuiteClassExclude
public class PlanMenu_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  protected static ExecutorService executor; 

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.View.PlanMenu"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    executor.shutdownNow(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
    org.evosuite.runtime.util.SystemInUtil.getInstance().initForTestCase(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/gongas/Desktop/3ano2sem/ATS_Aulas/ATS/SpotifyUM"); 
    java.lang.System.setProperty("user.home", "/home/gongas"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "gongas"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PlanMenu_ESTest_scaffolding.class.getClassLoader() ,
      "net.bytebuddy.description.TypeVariableSource$AbstractBase",
      "org.Model.SpotifUM",
      "net.bytebuddy.description.type.TypeList$Generic",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.description.annotation.AnnotationList",
      "org.View.AdminMenu",
      "net.bytebuddy.description.method.MethodList",
      "org.Controller.dtos.MusicInfo",
      "org.Model.Plan.PlanPremiumTop",
      "net.jqwik.api.lifecycle.LifecycleHook",
      "net.jqwik.api.lifecycle.PropertyAttributes",
      "net.jqwik.engine.discovery.predicates.IsContainerAGroup",
      "net.jqwik.api.ShrinkingMode",
      "org.Model.Plan.PlanFree",
      "net.bytebuddy.description.modifier.ModifierContributor$ForField",
      "net.bytebuddy.description.ModifierReviewable$ForFieldDescription",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver",
      "org.Exceptions.NotFoundException",
      "net.jqwik.engine.execution.ParameterSupplierResolver",
      "org.View.PlanMenu",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "org.Model.Album.Album",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.jqwik.engine.execution.DefaultTryLifecycleContext",
      "net.bytebuddy.description.method.MethodDescription$InDefinedShape",
      "net.jqwik.api.providers.TypeUsage",
      "org.Exceptions.NoArtistsInDatabaseException",
      "net.bytebuddy.description.type.TypeDescription$Generic$Visitor",
      "net.bytebuddy.jar.asm.MethodWriter",
      "org.View.Menu",
      "net.bytebuddy.description.modifier.Ownership",
      "net.bytebuddy.jar.asm.MethodTooLargeException",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher",
      "org.View.ProfileEditorMenu",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "net.bytebuddy.description.method.MethodDescription",
      "org.Exceptions.EmptyPlaylistException",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "net.bytebuddy.description.type.TypeList",
      "net.bytebuddy.implementation.attribute.AnnotationValueFilter",
      "net.jqwik.engine.execution.reporting.LineReporter",
      "net.bytebuddy.description.type.TypeList$Generic$ForLoadedTypes",
      "net.jqwik.engine.support.MethodParameter",
      "net.bytebuddy.description.modifier.ModifierContributor",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "net.bytebuddy.jar.asm.ClassTooLargeException",
      "net.bytebuddy.jar.asm.ModuleVisitor",
      "org.View.PlaylistCreationMenu",
      "net.bytebuddy.description.ModifierReviewable$AbstractBase",
      "net.bytebuddy.description.type.TypeDescription",
      "net.jqwik.api.constraints.UniqueElements",
      "net.bytebuddy.implementation.bytecode.ByteCodeAppender",
      "net.bytebuddy.implementation.bytecode.StackSize",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "org.Exceptions.NoMusicsInDatabaseException",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "net.bytebuddy.description.type.RecordComponentList",
      "net.bytebuddy.jar.asm.RecordComponentVisitor",
      "net.bytebuddy.description.type.TypeList$AbstractBase",
      "net.bytebuddy.description.modifier.ModifierContributor$ForMethod",
      "net.jqwik.api.Reporter",
      "net.bytebuddy.description.modifier.ModifierContributor$ForParameter",
      "org.View.MenuManager",
      "net.bytebuddy.jar.asm.ModuleWriter",
      "net.jqwik.api.lifecycle.PropertyLifecycleContext",
      "org.Model.Plan.PlanPremiumBase",
      "net.bytebuddy.description.modifier.TypeManifestation",
      "org.apiguardian.api.API",
      "net.jqwik.api.AfterFailureMode",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForDynamicTypeHash",
      "net.bytebuddy.matcher.ElementMatcher",
      "net.bytebuddy.description.NamedElement$WithGenericName",
      "net.bytebuddy.implementation.HashCodeMethod",
      "org.Model.Playlist.PlaylistCreator",
      "org.Exceptions.NoUsersInDatabaseException",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.description.type.TypeList$Generic$AbstractBase",
      "net.bytebuddy.description.modifier.SyntheticState",
      "org.Exceptions.NoReproductionsInDatabaseException",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.utility.MethodComparator",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.jqwik.api.lifecycle.PropagationMode",
      "net.bytebuddy.utility.Invoker",
      "org.View.ReproductionMenu$PlayerAction",
      "net.bytebuddy.description.ModifierReviewable$ForMethodDescription",
      "net.bytebuddy.dynamic.DynamicType$Builder",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "net.jqwik.api.EdgeCasesMode",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.matcher.FilterableList$Empty",
      "net.bytebuddy.implementation.Implementation$Target",
      "net.bytebuddy.description.modifier.Visibility",
      "net.bytebuddy.description.modifier.EnumerationState",
      "net.bytebuddy.description.type.RecordComponentList$ForLoadedRecordComponents",
      "net.jqwik.engine.descriptor.JqwikDescriptor",
      "net.bytebuddy.dynamic.ClassFileLocator",
      "org.Model.User.User",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "org.Model.Playlist.PlaylistRandom",
      "net.bytebuddy.description.field.FieldList",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "net.bytebuddy.description.modifier.ModifierContributor$ForType",
      "org.View.ProfileMenu",
      "net.bytebuddy.description.type.RecordComponentList$Empty",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Defaults",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.jqwik.api.lifecycle.LifecycleContext",
      "net.jqwik.api.GenerationMode",
      "net.bytebuddy.jar.asm.RecordComponentWriter",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.description.type.PackageDescription",
      "org.View.ReproductionMenu",
      "net.jqwik.engine.execution.DefaultPropertyLifecycleContext",
      "net.bytebuddy.implementation.bytecode.StackManipulation",
      "org.Model.Playlist.PlaylistFavorites",
      "net.bytebuddy.build.Plugin",
      "net.jqwik.engine.execution.AbstractLifecycleContext",
      "net.bytebuddy.description.TypeVariableSource$Visitor",
      "org.View.LoginMenu",
      "org.apiguardian.api.API$Status",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForStaticTypeHash",
      "org.View.StatisticsMenu",
      "net.bytebuddy.build.Plugin$Factory",
      "net.bytebuddy.description.type.TypeDescription$LazyProxy",
      "net.bytebuddy.matcher.FilterableList",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "org.Controller.Controller",
      "org.Model.Music.MusicMultimedia",
      "net.jqwik.api.lifecycle.TryLifecycleContext",
      "net.jqwik.api.lifecycle.ParameterResolutionContext",
      "net.jqwik.engine.discovery.predicates.IsTopLevelClass",
      "net.bytebuddy.description.type.TypeDescription$AbstractBase",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.description.ByteCodeElement$TypeDependant",
      "net.bytebuddy.jar.asm.FieldWriter",
      "org.Model.Playlist.Playlist",
      "org.Model.Plan.Plan",
      "net.bytebuddy.description.ModifierReviewable$ForParameterDescription",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Proxied",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider",
      "net.bytebuddy.description.TypeVariableSource",
      "net.bytebuddy.description.type.TypeDescription$Generic",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.jqwik.engine.execution.reporting.DefaultReporter",
      "net.bytebuddy.jar.asm.Frame",
      "org.Utils.Serialization",
      "net.jqwik.api.lifecycle.ResolveParameterHook",
      "org.Exceptions.NoPremissionException",
      "net.bytebuddy.description.type.TypeDefinition",
      "org.Model.Music.Music",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.ClassFileVersion",
      "net.bytebuddy.description.type.TypeList$Empty",
      "org.View.MainMenu",
      "net.bytebuddy.description.type.RecordComponentList$AbstractBase",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.description.ByteCodeElement",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType$Dispatcher",
      "net.jqwik.api.constraints.UniqueElements$NOT_SET",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.jar.asm.FieldVisitor",
      "net.bytebuddy.description.type.TypeDefinition$Sort",
      "org.Exceptions.AlreadyExistsException",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.implementation.EqualsMethod",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "net.bytebuddy.ClassFileVersion$VersionLocator",
      "net.bytebuddy.description.type.TypeList$ForLoadedTypes",
      "net.jqwik.engine.descriptor.ContainerClassDescriptor",
      "net.bytebuddy.jar.asm.Symbol",
      "net.jqwik.api.FixedSeedMode",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType",
      "org.View.PlaylistMenu",
      "net.bytebuddy.description.DeclaredByType$WithMandatoryDeclaration",
      "net.bytebuddy.matcher.FilterableList$AbstractBase",
      "net.bytebuddy.jar.asm.CurrentFrame",
      "org.Model.Music.MusicReproduction",
      "net.bytebuddy.utility.GraalImageCode",
      "net.bytebuddy.description.NamedElement"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PlanMenu_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.View.Menu",
      "org.View.PlanMenu",
      "org.apiguardian.api.API$Status",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.jqwik.api.EdgeCasesMode",
      "net.jqwik.api.FixedSeedMode",
      "net.jqwik.api.AfterFailureMode",
      "net.jqwik.api.ShrinkingMode",
      "net.jqwik.api.GenerationMode",
      "net.jqwik.api.lifecycle.PropagationMode",
      "org.Model.SpotifUM",
      "org.Controller.Controller",
      "org.View.MenuManager",
      "org.View.LoginMenu",
      "org.Model.Plan.Plan",
      "org.Model.Plan.PlanFree",
      "org.Model.User.User",
      "org.Model.Plan.PlanPremiumTop",
      "org.Model.Plan.PlanPremiumBase",
      "org.Utils.Serialization",
      "org.View.StatisticsMenu",
      "org.Model.Playlist.Playlist",
      "org.Model.Playlist.PlaylistRandom",
      "org.Exceptions.NoUsersInDatabaseException",
      "org.Exceptions.NotFoundException",
      "org.Exceptions.NoReproductionsInDatabaseException",
      "org.View.AdminMenu",
      "org.View.PlaylistCreationMenu",
      "org.Model.Album.Album",
      "org.Controller.dtos.MusicInfo",
      "org.View.MainMenu",
      "org.View.PlaylistMenu",
      "org.View.ReproductionMenu",
      "org.Model.Music.Music",
      "org.Model.Music.MusicMultimedia",
      "org.View.ProfileMenu",
      "org.Exceptions.NoMusicsInDatabaseException",
      "org.View.ProfileEditorMenu",
      "org.Exceptions.NoArtistsInDatabaseException",
      "org.Model.Music.MusicReproduction",
      "net.jqwik.engine.execution.DefaultTryLifecycleContext",
      "net.jqwik.api.constraints.UniqueElements$NOT_SET",
      "org.Model.Playlist.PlaylistCreator",
      "org.Model.Playlist.PlaylistFavorites",
      "net.jqwik.engine.execution.reporting.DefaultReporter",
      "net.jqwik.api.lifecycle.ResolveParameterHook",
      "net.jqwik.engine.execution.AbstractLifecycleContext",
      "net.jqwik.engine.execution.DefaultPropertyLifecycleContext",
      "net.jqwik.engine.execution.ParameterSupplierResolver"
    );
  }
}
