/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 23 15:01:00 GMT 2026
 */

package org.Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.Controller.Controller;
import org.Controller.dtos.MusicInfo;
import org.Model.SpotifUM;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Controller_ESTest extends Controller_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createGenrePlaylist("Letra: ", "Astro'\nYeah\nSun is down, freezing cold", 0);
      assertEquals("\u274C Erro ao criar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = controller0.getPlaylistMusicNames(1386);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Controller controller0 = new Controller();
      SpotifUM spotifUM0 = new SpotifUM();
      controller0.setSpotifUM(spotifUM0);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\u274C Erro ao listar playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllMusics();
      assertEquals("\u274C Erro ao listar m\u00FAsicas: null", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllGenres();
      assertEquals("\u274C Erro ao listar g\u00E9neros: null", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllAlbums();
      assertEquals("\u274C Erro ao listar \u00E1lbuns: null", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostReproductions();
      assertEquals("\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("m|", "H8,2A<V$X9Mun", "m|", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostPoints();
      assertEquals("\uD83C\uDFC6 Utilizador com mais pontos: m| com 0 pontos.", string1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostPlaylists();
      assertEquals("\u274C Erro ao obter o utilizador com mais playlists: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      Optional<List<String>> optional0 = controller0.getRandomPlaylistMusicNames();
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.getPublicPlaylistCount();
      assertEquals("\u274C Erro ao obter o n\u00FAmero de playlists p\u00FAblicas: null", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("1h9h`1K~AQ/Vx&$3", "\u274C Erro ao exportar a base de dados: Erro ao exportar o objeto: Error in writing to file", "FAIL", "H&:*}q$=3lGu2_", "FAIL", "G<PDsuRsXF", "\u274C Erro ao exportar a base de dados: Erro ao exportar o objeto: Error in writing to file", (-1), false, "1]<'y=Xw$Zxn");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      String string1 = controller0.getMostReproducedMusic();
      assertEquals("\uD83C\uDFB5 M\u00FAsica mais reproduzida: 1h9h`1K~AQ/Vx&$3 - \u274C Erro ao exportar a base de dados: Erro ao exportar o objeto: Error in writing to file", string1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = controller0.getAlbumMusicNames("\u274C Erro ao remover a m\u00FAsica da playlist: N\u00E3o encontrado: HXqQyVg%#f2");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.createAlbum("", "(X");
      assertEquals("\u274C Erro ao criar o \u00E1lbum: null", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createAlbum((String) null, " reprodu\u00E7\u00F5es.");
      assertEquals("\u2705 \u00C1lbum \"null\" criado com sucesso!", string0);
      
      String string1 = controller0.addMusic("", (String) null, "[A\u0004nf'J)/Fd<<ZSJ", "G", "f4Y]9nqD99|aqdbyze", "\uD83D\uDCED N\u00E3o existem playlists p\u00FAblicas.", (String) null, (-40), false, "\u274C Erro ao listar g\u00E9neros: ");
      assertEquals("\u2705 M\u00FAsica \"\" adicionada com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      MusicInfo musicInfo0 = controller0.playMusic("");
      assertNull(musicInfo0.getErrorMessage());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listUserPlaylists();
      assertEquals("\u274C Erro ao listar playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listPlaylistMusics((-2129));
      assertEquals("\u274C Erro ao listar m\u00FAsicas da playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Controller controller0 = new Controller();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2147483647L);
      String string0 = controller0.getUserWithMostReproductions(localDate0, (LocalDate) null);
      assertEquals("\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Controller controller0 = new Controller();
      SpotifUM spotifUM0 = controller0.getSpotifUM();
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = controller0.getFavoritePlaylistMusicNames(false, 390);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.musicExists(",date =");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.currentUserHasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.albumExists("yeP[<aK!z}LbuzCft");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.addNewUser("\u274C Erro ao listar playlists: null", (String) null, "\u274C Erro ao exportar a base de dados: ", "(9kNU$$b.l4");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Controller controller0 = null;
      try {
        controller0 = new Controller((Controller) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      SpotifUM spotifUM0 = controller0.getSpotifUM();
      assertNull(spotifUM0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("H&:*}q$=3lGu2_", "H&:*}q$=3lGu2_", "H&:*}q$=3lGu2_", "H&:*}q$=3lGu2_");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostReproductions();
      assertEquals("N\u00E3o existe utilizadores com reprodu\u00E7\u00F5es.", string1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addMusic("7ZfQ", "7ZfQ", "7ZfQ", "7ZfQ", "N\u00E3o existe utilizadores com playlists.", "7ZfQ", "7ZfQ", 2147483645, false, "");
      Optional<List<String>> optional0 = controller0.getRandomPlaylistMusicNames();
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.createAlbum((String) null, " reprodu\u00E7\u00F5es.");
      Optional<List<String>> optional0 = controller0.getAlbumMusicNames((String) null);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllGenres();
      assertEquals("\uD83D\uDCED N\u00E3o existem g\u00E9neros dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("Tim", "ZXYC.H*].ZxVV", "Tim", "", "ZXYC.H*].ZxVV", "Tim", "", (-40), false, "ZXYC.H*].ZxVV");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      String string1 = controller0.listAllGenres();
      assertEquals("\uD83C\uDFB6 Lista de g\u00E9neros dispon\u00EDveis:\n\n\u2022 Tim\n", string1);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllAlbums();
      assertEquals("\uD83D\uDCED N\u00E3o existem \u00E1lbuns dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createAlbum("M3RTXqX_", "M3RTXqX_");
      assertEquals("\u2705 \u00C1lbum \"M3RTXqX_\" criado com sucesso!", string0);
      
      String string1 = controller0.listAllAlbums();
      assertEquals("\uD83D\uDDBC\uFE0F  Lista de \u00E1lbuns dispon\u00EDveis:\n\n\uD83D\uDCC0 M3RTXqX_ \u2014 M3RTXqX_\n", string1);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllMusics();
      assertEquals("\uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\uD83D\uDCED N\u00E3o existem playlists p\u00FAblicas.", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.currentUserHasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", (String) null, "", (String) null);
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostPlaylists();
      assertEquals("N\u00E3o existe utilizadores com playlists.", string1);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.setSpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.getPublicPlaylistCount();
      assertEquals("\uD83D\uDCCA N\u00FAmero de playlists p\u00FAblicas: 0", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusicToCurrentUserPlaylist(20, "\uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis.");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica \u00E0 playlist: N\u00E3o encontrado: \uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.getCurrentUserPlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.musicExists("A H/-`W f");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.setPlaylistAsPublic(294);
      assertEquals("\u274C Erro ao definir a playlist como p\u00FAblica: null", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setPremiumTopPlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.changeCurrentUserUserName((String) null);
      assertEquals("\u274C Erro ao alterar o nome de utilizador: null", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.albumExists("\u274C Erro ao adicionar a m\u00FAsica \u00E0 playlist: N\u00E3o encontrado: \u274C Erro ao obter o nome da playlist: null");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostPoints();
      assertEquals("\u274C Erro ao obter o utilizador com mais pontos: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.getCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.changeCurrentUserPassword("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addPublicPlaylistToLibrary(47);
      assertEquals("\u274C Erro ao adicionar a playlist \u00E0 biblioteca: N\u00E3o encontrado: 47", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedMusic();
      assertEquals("\u274C Erro ao obter a m\u00FAsica mais reproduzida: N\u00E3o existem m\u00FAsicas na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.isPasswordCorrect("\u274C Erro ao obter o nome da playlist: null");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.removeMusicFromPlaylist("v.gly5N]S0v`NJz", 642);
      assertEquals("\u274C Erro ao remover a m\u00FAsica da playlist: N\u00E3o encontrado: v.gly5N]S0v`NJz", string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("7ZfQ", "7ZfQ", "7ZfQ", "7ZfQ", "N\u00E3o existe utilizadores com playlists.", "7ZfQ", "7ZfQ", 2147483645, false, "");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      String string1 = controller0.listAllMusics();
      assertEquals("\uD83C\uDFB5 Lista de m\u00FAsicas dispon\u00EDveis:\n\n\uD83C\uDFB6 7ZfQ \u2014 7ZfQ\n", string1);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getPlaylistId(2147483645);
      assertEquals("\u274C Erro ao obter o nome da playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.changeCurrentUserEmail("\u274C Erro ao obter o utilizador com mais pontos: N\u00E3o existem utilizadores na base de dados.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setPremiumBasePlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.exportModel("");
      assertEquals("\u274C Erro ao exportar a base de dados: Erro ao exportar o objeto: null", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedArtist();
      assertEquals("\u274C Erro ao obter o artista mais reproduzido: N\u00E3o existem artistas na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Controller controller0 = new Controller();
      Controller controller1 = new Controller(controller0);
      assertFalse(controller1.equals((Object)controller0));
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedGenre();
      assertEquals("\u274C Erro ao obter o g\u00E9nero mais reproduzido: N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.importModel("");
      assertEquals("\u274C Erro ao importar a base de dados: Erro ao importar o objeto: null", string0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      boolean boolean0 = controller0.loginWithMessage("\u274C Erro ao listar g\u00E9neros: null", "Failed to create invoker for ");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addToCurrentUserPlaylists("v.gly5N]S0v`NJz");
      assertEquals("\u274C Erro ao adicionar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setFreePlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }
}
