/*
 * This file was automatically generated by EvoSuite
 * Fri May 08 18:17:01 GMT 2026
 */

package org.Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.Controller.Controller;
import org.Controller.dtos.MusicInfo;
import org.Model.SpotifUM;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Controller_ESTest extends Controller_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Controller controller0 = new Controller();
      LocalDate localDate0 = MockLocalDate.now();
      String string0 = controller0.getUserWithMostReproductions((LocalDate) null, localDate0);
      assertEquals("\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createAlbum("O w?L", "QH}WwK/<S}FrY");
      assertEquals("\u2705 \u00C1lbum \"O w?L\" criado com sucesso!", string0);
      
      String string1 = controller0.addMusic("net.bytebuddy.implementation.auxiliary.AuxiliaryType", "O w?L", (String) null, (String) null, "6;*2?hIi/XEXH03v", "", "O w?L", 923, false, "%1w%-P.40epF5u");
      assertEquals("\u2705 M\u00FAsica \"net.bytebuddy.implementation.auxiliary.AuxiliaryType\" adicionada com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("", "", "*698{9iw2V-gi07@v`s", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", (-44), true, "");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Controller controller0 = new Controller();
      SpotifUM spotifUM0 = new SpotifUM();
      controller0.setSpotifUM(spotifUM0);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("", "", "e`4)L", "Ex23m");
      spotifUM0.setCurrentUser(user0);
      Controller controller0 = new Controller(spotifUM0);
      MusicInfo musicInfo0 = controller0.playMusic("T'Sbu*A4`on");
      assertEquals("N\u00E3o encontrado: T'Sbu*A4`on", musicInfo0.getErrorMessage());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listUserPlaylists();
      assertEquals("\u274C Erro ao listar playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\u274C Erro ao listar playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listPlaylistMusics(0);
      assertEquals("\u274C Erro ao listar m\u00FAsicas da playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllMusics();
      assertEquals("\u274C Erro ao listar m\u00FAsicas: null", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllGenres();
      assertEquals("\u274C Erro ao listar g\u00E9neros: null", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllAlbums();
      assertEquals("\u274C Erro ao listar \u00E1lbuns: null", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostReproductions();
      assertEquals("\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("\u274C Erro ao obter o utilizador com mais pontos: N\u00E3o existem utilizadores na base de dados.", "", "", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostPoints();
      assertEquals("\uD83C\uDFC6 Utilizador com mais pontos: \u274C Erro ao obter o utilizador com mais pontos: N\u00E3o existem utilizadores na base de dados. com 0 pontos.", string1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.getUserWithMostPlaylists();
      assertEquals("\u274C Erro ao obter o utilizador com mais playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      Optional<List<String>> optional0 = (Optional<List<String>>)controller0.getRandomPlaylistMusicNames();
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.getPublicPlaylistCount();
      assertEquals("\u274C Erro ao obter o n\u00FAmero de playlists p\u00FAblicas: null", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("", "", "kW}M", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", (-44), true, "");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      String string1 = controller0.getMostReproducedMusic();
      assertEquals("\uD83C\uDFB5 M\u00FAsica mais reproduzida:  - ", string1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("");
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.getMostReproducedGenre();
      assertEquals("\uD83C\uDFB6 G\u00E9nero mais reproduzido: ", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      Optional<List<String>> optional0 = controller0.getFavoritePlaylistMusicNames(true, (-3790));
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      Optional<List<String>> optional0 = (Optional<List<String>>)controller0.getAlbumMusicNames("\u274C Erro ao obter o g\u00E9nero mais reproduzido: null");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.createAlbum("AUTO", "AUTO");
      assertEquals("\u274C Erro ao criar o \u00E1lbum: null", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.changeCurrentUserUserName("\uD83D\uDCDA Utilizador com mais playlists: ");
      assertEquals("\u2705 Nome de utilizador alterado com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      assertEquals("\u2728 Plano PremiumBase ativado. Boa escolha!", string1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setFreePlan();
      assertEquals("\u2705 Plano Free selecionado. Desfrute da m\u00FAsica com an\u00FAncios!", string1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("", "", "\u274C Erro ao adicionar a playlist: null", "", "", "gIw-VoUxC", "$>I8;Lo;#nr#", 904, false, (String) null);
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      boolean boolean0 = controller0.musicExists("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.isPasswordCorrect("\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.isPasswordCorrect("#A_z!=7*GaECL=q");
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      SpotifUM spotifUM0 = controller0.getSpotifUM();
      assertNull(spotifUM0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      spotifUM0.populateDatabase();
      SpotifUM spotifUM1 = controller0.getSpotifUM();
      assertSame(spotifUM1, spotifUM0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = (Optional<List<String>>)controller0.getPlaylistMusicNames(215);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      String string0 = controller0.getCurrentUserPlan();
      assertEquals("Free", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.getCurrentUser();
      assertEquals("\uD83D\uDCC4 Informa\u00E7\u00F5es do Perfil:\n\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DADOS DO UTILIZADOR \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\n  \uD83D\uDC64 Nome de Utilizador: :$\n  \uD83D\uDCE7 Email: :$\n  \uD83C\uDFE0 Morada: #A_z!=7*GaECL=q\n  \uD83D\uDD11 Password: \u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\n  \uD83D\uDCCB Plano: Plano: Free\n    Pontos: 0\n\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D", string1);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":", ":", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      boolean boolean1 = controller0.currentUserAccessToFavorites();
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      User user0 = new User("FlA!6,<4XX-`K(%b", "", "FlA!6,<4XX-`K(%b", "5h%0n\"Zmoe");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = controller0.currentUserAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.changeCurrentUserPassword(":$");
      assertEquals("\u2705 Password alterada com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      User user0 = new User("FlA!6,<4XX-`K(%b", "", "FlA!6,<4XX-`K(%b", "5h%0n\"Zmoe");
      spotifUM0.setCurrentUser(user0);
      String string0 = controller0.changeCurrentUserEmail("");
      assertEquals("\u2705 Email alterado com sucesso!", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      boolean boolean1 = controller0.canCurrentUserSkip();
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.canCurrentUserSkip();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "\u274C Erro ao adicionar a playlist: null", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      boolean boolean1 = controller0.canCurrentUserChooseWhatToPlay();
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.canCurrentUserChooseWhatToPlay();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      spotifUM0.populateDatabase();
      boolean boolean0 = controller0.albumExists("Hotel California");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.musicExists("\u274C Erro ao exportar a base de dados: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.currentUserHasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.albumExists(")ao57dXHc\"UI3!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.addNewUser("", "", "", "cr4A");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Controller controller0 = null;
      try {
        controller0 = new Controller((Controller) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Controller controller0 = new Controller();
      SpotifUM spotifUM0 = controller0.getSpotifUM();
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostReproductions();
      assertEquals("N\u00E3o existe utilizadores com reprodu\u00E7\u00F5es.", string1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("\u274C Erro ao exportar a base de dados: Erro ao exportar o objeto: Error in writing to file", "", "\" adicionada \u00E0 lista de playlists do utilizador.", "\uD83C\uDFB5 Lista de m\u00FAsicas dispon\u00EDveis:\n\n");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostPlaylists();
      assertEquals("N\u00E3o existe utilizadores com playlists.", string1);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      String string2 = controller0.addToCurrentUserPlaylists("H}DS!/3");
      assertEquals("\u2705 Playlist \"H}DS!/3\" adicionada \u00E0 lista de playlists do utilizador.", string2);
      
      String string3 = controller0.getUserWithMostPlaylists();
      assertEquals("\uD83D\uDCDA Utilizador com mais playlists: :$ com 1 playlists.", string3);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addMusic("", "", "kW}M", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", (-44), true, "");
      Optional<List<String>> optional0 = (Optional<List<String>>)controller0.getRandomPlaylistMusicNames();
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      Optional<List<String>> optional0 = (Optional<List<String>>)controller0.getFavoritePlaylistMusicNames(true, (-1));
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.createAlbum("net.bytebuddy.implementation.auxiliary.AuxiliaryType", "QH}WwK/<S}FrY");
      controller0.addMusic("net.bytebuddy.implementation.auxiliary.AuxiliaryType", "net.bytebuddy.implementation.auxiliary.AuxiliaryType", (String) null, (String) null, "net.bytebuddy.implementation.auxiliary.AuxiliaryType", (String) null, "net.bytebuddy.implementation.auxiliary.AuxiliaryType", 923, false, "net.bytebuddy.implementation.auxiliary.AuxiliaryType");
      Optional<List<String>> optional0 = (Optional<List<String>>)controller0.getAlbumMusicNames("net.bytebuddy.implementation.auxiliary.AuxiliaryType");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllGenres();
      assertEquals("\uD83D\uDCED N\u00E3o existem g\u00E9neros dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("K{", "K{", "\u274C Erro ao adicionar a playlist: null", "\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", ";F>t;iZ6lyV%$tt", "", "$>I8;Lo;#nr#", 886, false, "K{");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      String string1 = controller0.listAllGenres();
      assertEquals("\uD83C\uDFB6 Lista de g\u00E9neros dispon\u00EDveis:\n\n\u2022 \n", string1);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllAlbums();
      assertEquals("\uD83D\uDCED N\u00E3o existem \u00E1lbuns dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewAlbum("", "");
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.listAllAlbums();
      assertEquals("\uD83D\uDDBC\uFE0F  Lista de \u00E1lbuns dispon\u00EDveis:\n\n\uD83D\uDCC0  \u2014 \n", string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      String string2 = controller0.listPlaylistMusics((-342));
      assertEquals("\uD83C\uDFB5 Lista de m\u00FAsicas na playlist:\n\nN\u00E3o encontrado: -342", string2);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.listAllMusics();
      assertEquals("\uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\uD83D\uDCED N\u00E3o existem playlists p\u00FAblicas.", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      spotifUM0.addPlaylist("\uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis.", "\u274C Erro ao obter o nome da playlist: null");
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\uD83D\uDCDA Playlists P\u00FAblicas:\n\uD83C\uDFB5 [#000] \uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis. | Autor: \u274C Erro ao obter o nome da playlist: null\n", string0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      String string2 = controller0.listUserPlaylists();
      assertEquals("\uD83D\uDCED N\u00E3o existem playlists.", string2);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      String string2 = controller0.addToCurrentUserPlaylists("H}DS!/3");
      assertEquals("\u2705 Playlist \"H}DS!/3\" adicionada \u00E0 lista de playlists do utilizador.", string2);
      
      String string3 = controller0.listUserPlaylists();
      assertEquals("\uD83D\uDCDA As tuas playlists:\n\uD83C\uDFB5 [#000] H}DS!/3                   | Autor: :$             \n", string3);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      boolean boolean1 = controller0.currentUserHasLibrary();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      boolean boolean0 = controller0.currentUserHasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "\u274C Erro ao adicionar a playlist: null", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.addNewUser(":$", "\u274C Erro ao adicionar a playlist: null", ":$", "\u2705 Password alterada com sucesso!");
      assertEquals("\u26A0\uFE0F J\u00E1 existe um utilizador com esse nome. Tenta outro!", string1);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser(":$", ":$", "#A_z!=7*GaECL=q", "\u274C Erro ao adicionar a playlist: null");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      boolean boolean1 = controller0.currentUserHasLibrary();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setSpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.getPublicPlaylistCount();
      assertEquals("\uD83D\uDCCA N\u00FAmero de playlists p\u00FAblicas: 0", string0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusicToCurrentUserPlaylist(904, "\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica \u00E0 playlist: N\u00E3o encontrado: \u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.getCurrentUserPlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.musicExists((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.setPlaylistAsPublic((-998));
      assertEquals("\u274C Erro ao definir a playlist como p\u00FAblica: null", string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setPremiumTopPlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.changeCurrentUserUserName("\uD83D\uDCDA Utilizador com mais playlists: ");
      assertEquals("\u274C Erro ao alterar o nome de utilizador: null", string0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      boolean boolean0 = controller0.albumExists("Hotel California");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostPoints();
      assertEquals("\u274C Erro ao obter o utilizador com mais pontos: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      // Undeclared exception!
      try { 
        controller0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createGenrePlaylist("Y<", "ZMMtNDz", (-1411));
      assertEquals("\u274C Erro ao criar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.getCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.changeCurrentUserPassword("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addPublicPlaylistToLibrary((-1));
      assertEquals("\u274C Erro ao adicionar a playlist \u00E0 biblioteca: N\u00E3o encontrado: -1", string0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedMusic();
      assertEquals("\u274C Erro ao obter a m\u00FAsica mais reproduzida: N\u00E3o existem m\u00FAsicas na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.isPasswordCorrect("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.removeMusicFromPlaylist("\u274C Erro ao adicionar a playlist: null", 899);
      assertEquals("\u274C Erro ao remover a m\u00FAsica da playlist: N\u00E3o encontrado: \u274C Erro ao adicionar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusic("", "", "kW}M", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", "N\u00E3o existem utilizadores na base de dados.", "net.jqwik.engine.support.types.TypeUsageImpl", (-44), true, "");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica: null", string0);
      
      String string1 = controller0.listAllMusics();
      assertEquals("\uD83C\uDFB5 Lista de m\u00FAsicas dispon\u00EDveis:\n\n\uD83C\uDFB6  \u2014 \n", string1);
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getPlaylistId((-1));
      assertEquals("\u274C Erro ao obter o nome da playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      // Undeclared exception!
      try { 
        controller0.changeCurrentUserEmail("\uD83C\uDFB6 G\u00E9nero mais reproduzido: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setPremiumBasePlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.exportModel("");
      assertEquals("\u274C Erro ao exportar a base de dados: Erro ao exportar o objeto: null", string0);
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedArtist();
      assertEquals("\u274C Erro ao obter o artista mais reproduzido: N\u00E3o existem artistas na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      Controller controller0 = new Controller();
      Controller controller1 = new Controller(controller0);
      assertFalse(controller1.equals((Object)controller0));
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedGenre();
      assertEquals("\u274C Erro ao obter o g\u00E9nero mais reproduzido: N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.importModel("\u274C Erro ao listar m\u00FAsicas: ");
      assertEquals("\u274C Erro ao importar a base de dados: Erro ao importar o objeto: null", string0);
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.loginWithMessage(":$", "\u274C Erro ao adicionar a playlist: null");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addToCurrentUserPlaylists(":$");
      assertEquals("\u274C Erro ao adicionar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test98()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setFreePlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }
}
