/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 12:30:23 GMT 2026
 */

package org.Model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistFavorites;
import org.Model.Playlist.PlaylistRandom;
import org.Model.SpotifUM;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SpotifUM_ESTest extends SpotifUM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      LocalDate localDate0 = MockLocalDate.ofYearDay(1920, 167);
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, (LocalDate) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addPlaylist("N\u00E3o encontrado: ", "");
      assertEquals(1, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("", "Portuguese Pride", "Portuguese Pride", "", ":}j*gq>", "", "Michael Jackson", 1773, true, "Michael Jackson");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic((String) null, "iy4J$ap", "<Vah,Z)", "4}a'UkqAJDy]'-sjd", "4}a'UkqAJDy]'-sjd", "iy4J$ap", "4}a'UkqAJDy]'-sjd", 203, true, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":*m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserPassword("Top Dawg");
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserEmail("hoqT,HDx+oA,");
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      Music music0 = spotifUM0.mostReproducedMusic();
      user0.addMusicReproduction(music0);
      spotifUM0.setCurrentUser(user0);
      PlaylistFavorites playlistFavorites0 = spotifUM0.createFavoritesPlaylist(1065, false);
      assertEquals("Feito para Voc\u00EA", playlistFavorites0.getName());
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.addToCurrentUserPlaylist(";)vUqEA7)2bP");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.addToCurrentUserMusicReproductions(";vUqEA7)2bP");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewAlbum((String) null, "net.jqwik.engine.discovery.predicates.IsTopLevelClass");
      spotifUM0.addNewMusic("/", (String) null, "includeSyntheticFields", " was expected to be virtual: ", "!])H*", " was expected to be virtual: ", (String) null, 3964, true, (String) null);
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      hashMap0.put("", music0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM(hashMap0, hashMap1, hashMap2, hashMap3, hashMap4, hashMap4);
      Music music1 = spotifUM0.mostReproducedMusic();
      assertEquals("", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.listCurrentUserPlaylists();
      assertEquals("\uD83C\uDFB5 [#006] My Mix                    | Autor: simao          \n\uD83C\uDFB5 [#007] Tesouros Portugueses      | Autor: simao          \n", string0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.listAllMusicsInPlaylist(91);
      assertEquals("N\u00E3o encontrado: 91", string0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.isPasswordCorrect("\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("net.jqwik.engine.descriptor.ContainerClassDescriptor", "net.jqwik.engine.descriptor.ContainerClassDescriptor", ":m..", "/FF/");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.hasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser((String) null, "9Pr", "", (String) null);
      Map<String, User> map0 = spotifUM0.getUsers();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertEquals(21, map0.size());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("+%&");
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.getCurrentUserPlanName();
      assertEquals("Free", string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("}+BZ]u>pxS S");
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.currentUserAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      PlaylistFavorites playlistFavorites0 = spotifUM0.createFavoritesPlaylist(1065, false);
      assertEquals("SpotifyUM", playlistFavorites0.getAutor());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("net.jqwik.engine.descriptor.ContainerClassDescriptor", "net.jqwik.engine.descriptor.ContainerClassDescriptor", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserSkip();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserChooseWhatToPlay();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserChooseWhatToPlay();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setUsers((Map<String, User>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPublicPlaylists((Map<Integer, Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPlaylistAsPublic((-2694));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setMusics((Map<String, Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setGenreReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setArtistReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setAlbums((Map<String, Album>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":m.", "VmOj>%G,x''{cBe");
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.listCurrentUserPlaylists();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o possuem playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.listAllMusicsInPlaylist(363);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listAllMusicsInPlaylist((-1152));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById(3124);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById((-398));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      Integer integer0 = hashMap0.put("hj8j*k54&--</:", (Integer) null);
      hashMap0.put("3BN\"} {#2", integer0);
      spotifUM0.setArtistReproductions(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      Integer integer0 = hashMap4.put("Vlru~pzE=", (Integer) null);
      hashMap4.put("\uD83C\uDFB5 [#000] Top Global                | Autor: Spotify        \n\uD83C\uDFB5 [#001] Rock Legends              | Autor: RockFM         \n\uD83C\uDFB5 [#002] Hip-Hop Nation            | Autor: HipHopTV       \n\uD83C\uDFB5 [#003] Electronic Vibes          | Autor: EDM.com        \n\uD83C\uDFB5 [#004] Throwback Hits            | Autor: OldiesFM       \n\uD83C\uDFB5 [#005] Portuguese Pride          | Autor: RTP            \n", integer0);
      SpotifUM spotifUM0 = new SpotifUM(hashMap0, hashMap1, hashMap2, hashMap3, hashMap4, hashMap4);
      // Undeclared exception!
      try { 
        spotifUM0.getGenreWithMostReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.changeCurrentUserName("net.jqwik.engine.descriptor.PropertyConfiguration");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      SpotifUM spotifUM0 = null;
      try {
        spotifUM0 = new SpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = spotifUM0.getCurrentUser();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, User> map0 = spotifUM0.getUsers();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Music> map0 = spotifUM0.getMusics();
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      Map<String, User> map1 = spotifUM0.getUsers();
      HashMap<String, Album> hashMap1 = new HashMap<String, Album>();
      SpotifUM spotifUM1 = null;
      try {
        spotifUM1 = new SpotifUM(map0, hashMap0, map1, hashMap1, (Map<String, Integer>) null, (Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      boolean boolean0 = spotifUM0.equals(spotifUM1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("}n", "\"=<haG", "\"=<haG", "");
      SpotifUM spotifUM1 = new SpotifUM();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addPlaylist("?Pb}jp%xf1", "?Pb}jp%xf1");
      SpotifUM spotifUM1 = new SpotifUM();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", "Hino do Futebol Clube do Porto\nCantado com orgulho e amor\nPor todos os portistas no mundo", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      SpotifUM spotifUM1 = new SpotifUM();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(spotifUM0.equals((Object)spotifUM1));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      spotifUM1.setCurrentUser(user0);
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertEquals(6, spotifUM1.getPublicPlaylistSize());
      assertFalse(spotifUM1.equals((Object)spotifUM0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.equals(spotifUM0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0);
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPlaylists();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      assertEquals("love@music.com", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getGenreWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      Integer integer0 = new Integer((-2842));
      hashMap4.put("Vlru~pzE=", integer0);
      SpotifUM spotifUM0 = new SpotifUM(hashMap0, hashMap1, hashMap2, hashMap3, hashMap4, hashMap4);
      String string0 = spotifUM0.getGenreWithMostReproductions();
      assertEquals("Vlru~pzE=", string0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPoints();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserUsername("VI/T_D");
      assertEquals(6, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem artistas na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      Integer integer0 = new Integer(2454);
      hashMap0.put("3BN\"} {#2", integer0);
      spotifUM0.setArtistReproductions(hashMap0);
      String string0 = spotifUM0.getTopArtistName();
      assertEquals("3BN\"} {#2 - 2454\n", string0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.mostReproducedMusic();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem m\u00FAsicas na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("\uD83C\uDFB5 [#000] Top Global                | Autor: Spotify        \n\uD83C\uDFB5 [#001] Rock Legends              | Autor: RockFM         \n\uD83C\uDFB5 [#002] Hip-Hop Nation            | Autor: HipHopTV       \n\uD83C\uDFB5 [#003] Electronic Vibes          | Autor: EDM.com        \n\uD83C\uDFB5 [#004] Throwback Hits            | Autor: OldiesFM       \n\uD83C\uDFB5 [#005] Portuguese Pride          | Autor: RTP            \n", string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addPlaylistToCurrentUserLibrary(1641);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 1641
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      try { 
        spotifUM0.addPlaylistToCurrentUserLibrary(1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: 1
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addMusicToCurrentUserPlaylist((-1908874352), ".9@rUc]X.j2Mv}");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: .9@rUc]X.j2Mv}
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 0 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 1 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Integer integer0 = new Integer((-3191));
      try { 
        spotifUM0.removeMusicFromPlaylist("Cannot cache the value of a method with parameters: ", integer0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: Cannot cache the value of a method with parameters: 
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("\uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa\n\uD83D\uDCC0 Scorpion \u2014 Drake\n\uD83D\uDCC0 Fine Line \u2014 Harry Styles\n\uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott\n\uD83D\uDCC0 Discovery \u2014 Daft Punk\n\uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar\n\uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem\n\uD83D\uDCC0 Rick Roll \u2014 Rick Astley\n\uD83D\uDCC0 Divide \u2014 Ed Sheeran\n\uD83D\uDCC0 A Night at the Opera \u2014 Queen\n\uD83D\uDCC0 After Hours \u2014 The Weeknd\n\uD83D\uDCC0 Hotel California \u2014 Eagles\n\uD83D\uDCC0 Thriller \u2014 Michael Jackson\n\uD83D\uDCC0 Tanto Porto! \u2014 FC Porto\n\uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin\n\uD83D\uDCC0 Starboy \u2014 The Weeknd\n\uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses\n\uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta\n\uD83D\uDCC0 Nevermind \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Music music0 = spotifUM0.mostReproducedMusic();
      try { 
        spotifUM0.addMusicToAlbum((String) null, music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: null
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getAlbumByName("Titanium");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: Titanium
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewAlbum("0d-'7Ft(-> $.L!z", "=zD@");
      Album album0 = spotifUM0.getAlbumByName("0d-'7Ft(-> $.L!z");
      assertEquals("=zD@", album0.getArtist());
      assertEquals("0d-'7Ft(-> $.L!z", album0.getName());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.albumExists("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("Playlist Favoritos{", "", ">G@H\"Ux<", ">G@H\"Ux<", "", "INSTANCE", "", 0, true, "Playlist Favoritos{");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getMusicByName("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.playMusic("net.bytebuddy.build.RepeatedAnnotationPlugin$RepeatedAnnotationAppender");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: net.bytebuddy.build.RepeatedAnnotationPlugin$RepeatedAnnotationAppender
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      hashMap0.put("ef<)1P?m", music0);
      spotifUM0.setMusics(hashMap0);
      boolean boolean0 = spotifUM0.musicExists("ef<)1P?m");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.musicExists("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.userExists("God's Plan");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser(":0Xn", ":0Xn", "", "z3\"maZeefrSmq2");
      try { 
        spotifUM0.authenticateUser(":0Xn", " was expected to be virtual: ");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Password incorreta.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.authenticateUser("a`x", "#E{+9|ZWBBEjtyu46");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: a`x
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("net.jqwik.engine.descriptor.ContainerClassDescriptor", "net.jqwik.engine.descriptor.ContainerClassDescriptor", ":m.", "/FF/");
      spotifUM0.setCurrentUser(user0);
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      assertTrue(spotifUM1.equals((Object)spotifUM0));
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createFavoritesPlaylist(1065, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserMusicReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getPublicPlaylistById(38);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById(3124);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist(";)vUqEA7)2bP", "\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n", 1065);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementArtistReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      spotifUM0.setGenreReproductions(hashMap0);
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserPassword("f50-!sv4lRjK(\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      spotifUM0.setPublicPlaylists(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserPlaylist((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listCurrentUserPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.toString();
      assertEquals("SpotifUM(...)", string0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.isPasswordCorrect("(ZN-!%");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      spotifUM0.setAlbums(hashMap0);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserUsername("v!(R7p_o");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserEmail(" m\u00FAsicas.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addPointsToCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      assertTrue(spotifUM1.equals((Object)spotifUM0));
      
      spotifUM0.populateDatabase();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist(";)vUqEA7)2bP", "\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n", 1065);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o existem m\u00FAsicas desse g\u00E9nero.
         //
         verifyException("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementGenreReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM(hashMap0, hashMap1, hashMap2, hashMap3, hashMap4, hashMap4);
      // Undeclared exception!
      try { 
        spotifUM0.getCurrentUserPlanName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }
}
