/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:46:45 GMT 2026
 */

package org.spotifumtp37.model.album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.Album;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.subscription.SubscriptionPlan;
import org.spotifumtp37.model.user.History;
import org.spotifumtp37.model.user.User;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      album0.addSong(", videolink='", "Ae>2_*_?UjI", ", durationinseconds=", "", "0qt!h6\" !V", 1, false, true, ", genre='");
      album0.addSong("0gT=|/4qRC0p6w{_89", "0gT=|/4qRC0p6w{_89", "X7aV|<_Lf[Y-O%HXYP~", "0gT=|/4qRC0p6w{_89", "0gT=|/4qRC0p6w{_89", 1389, true, false, "");
      album0.next(user0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("mM9{E", "mM9{E", "mM9{E", ">3~@/wN9~FY$:><)", "lgz.3w0I0vAKj 'Cj", 2879, false, false, "");
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("", "", "", premiumTop0, "", 1121.803067934622, linkedList0);
      album0.next(user0);
      album0.next(user0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong("org.spotifumtp37.model.subscription.FreePlan", "org.spotifumtp37.model.subscription.FreePlan", "org.spotifumtp37.model.subscription.FreePlan", "Song duration must be positive.", "3U5@dNlOU#", (-1263), true, true, "org.spotifumtp37.model.subscription.FreePlan");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song duration must be positive.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("2}t^0]", "Oi_-z", "Oi_-z", "Oi_-z", (String) null, 125, true, true, "");
      album0.setCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("\u0000U)PF\"{B1Wf9|\"N8)", ",w=-Y", (String) null, "b??>o#=9@", ",w=-Y", 3653, true, false, "b??>o#=9@");
      int int0 = album0.getTotalDuration();
      assertEquals(0, album0.getReleaseYear());
      assertEquals(3653, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Album album0 = new Album();
      album0.setTitle((String) null);
      album0.getTitle();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongs();
      Album album1 = new Album("Song duration must be positive.", "Song duration must be positive.", 0, ", artist='", list0);
      String string0 = album1.getTitle();
      assertEquals(0, album0.getReleaseYear());
      assertEquals("Song duration must be positive.", string0);
      assertEquals(", artist='", album1.getGenre());
      assertEquals("Song duration must be positive.", album1.getArtist());
      assertEquals(0, album1.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("\"GmpG]FE`]fm{j", "\"GmpG]FE`]fm{j", ", email='", "\"GmpG]FE`]fm{j", "\"GmpG]FE`]fm{j", 1368, false, false, "\"GmpG]FE`]fm{j");
      album0.getSongs();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Album album0 = new Album(", time=", "lbsI;}n", 2120, "", list0);
      int int0 = album0.getReleaseYear();
      assertEquals(", time=", album0.getTitle());
      assertEquals("lbsI;}n", album0.getArtist());
      assertEquals("", album0.getGenre());
      assertEquals(2120, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Album album0 = new Album();
      album0.setReleaseYear((-2490));
      int int0 = album0.getReleaseYear();
      assertEquals((-2490), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      Album album1 = new Album("", (String) null, 1276, (String) null, list0);
      String string0 = album1.getGenre();
      assertEquals(1276, album1.getReleaseYear());
      assertNull(string0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongs();
      Album album1 = new Album("VFl", "VFl", 1938, "*MX1C|B<Y?qVH?'", list0);
      String string0 = album1.getGenre();
      assertEquals("VFl", album1.getTitle());
      assertEquals("VFl", album1.getArtist());
      assertEquals(1938, album1.getReleaseYear());
      assertEquals("*MX1C|B<Y?qVH?'", string0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("mM9{E", "mM9{E", "mM9{E", ">3~@/wN9~FY$:><)", "lgz.3w0I0vAKj 'Cj", 2879, true, true, "");
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("", "", "", premiumTop0, "", 1121.803067934622, linkedList0);
      album0.next(user0);
      Song song0 = album0.getCurrentSong();
      assertEquals("lgz.3w0I0vAKj 'Cj", song0.getGenre());
      assertEquals("mM9{E", song0.getName());
      assertEquals(0, album0.getReleaseYear());
      assertEquals("mM9{E", song0.getPublisher());
      assertEquals(">3~@/wN9~FY$:><)", song0.getMusicalNotes());
      assertEquals(2879, song0.getDurationInSeconds());
      assertEquals("mM9{E", song0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      Song song0 = new Song();
      song0.incrementTimesPlayed();
      album0.setCurrentSong(song0);
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Album album0 = new Album();
      Song song0 = new Song("", "", "", "", "}", "}", (-1));
      album0.setCurrentSong(song0);
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album((String) null, (String) null, (-18), (String) null, linkedList0);
      album0.getArtist();
      assertEquals((-18), album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("mM9{E", "mM9{E", "mM9{E", "mM9{E", "", 2879, false, false, "");
      album0.deleteSong("mM9{E");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Album album0 = new Album();
      album0.setReleaseYear((-661));
      album0.clone();
      assertEquals((-661), album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.previous((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Album album0 = new Album();
      PremiumBase premiumBase0 = new PremiumBase();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User(", pontos=", ", pontos=", ", pontos=", premiumBase0, ", pontos=", 1891.8, linkedList0);
      // Undeclared exception!
      try { 
        album0.previous(user0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("", "nXTdF3", "nXTdF3", (SubscriptionPlan) null, "", (-17.9136896), list0);
      // Undeclared exception!
      try { 
        album0.play(user1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.user.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.nextShuffle();
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.next((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.copySongs((List<Song>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album((Album) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album("1Cof6>+=oDGNw2NL", "852wirKR=O7D", 0, "Y6G%~xI", (List<Song>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("\u0000U)PF\"{B1Wf9|\"N8)", ",w=-Y", (String) null, "b??>o#=9@", ",w=-Y", 3653, true, false, "b??>o#=9@");
      List<Song> list0 = album0.getSongsCopy();
      List<Song> list1 = album0.copySongs(list0);
      assertEquals(0, album0.getReleaseYear());
      assertNotSame(list1, list0);
      assertEquals(1, list1.size());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      List<Song> list1 = album0.copySongs(list0);
      assertEquals(0, album0.getReleaseYear());
      assertNotSame(list1, list0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Album album0 = new Album();
      album0.getGenre();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Album album0 = new Album();
      int int0 = album0.getReleaseYear();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = new Album(album0);
      assertEquals(0, album1.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongs();
      Album album1 = new Album("ZIvV0/TR r(", "ZIvV0/TR r(", 0, ",_xMD%", list0);
      String string0 = album1.getArtist();
      assertEquals(0, album1.getReleaseYear());
      assertEquals(0, album0.getReleaseYear());
      assertEquals(",_xMD%", album1.getGenre());
      assertEquals("ZIvV0/TR r(", string0);
      assertEquals("ZIvV0/TR r(", album1.getTitle());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Album album0 = new Album();
      album0.getArtist();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Album album0 = new Album();
      album0.getTitle();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("xq!gqK2v{c9S_L(", "h~;9jh#ri9s_*d9~3[ ", 966, "xq!gqK2v{c9S_L(", linkedList0);
      User user0 = new User();
      try { 
        album0.previous(user0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Your subscription does not allow going back in the playlist.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("mM9{E", "mM9{E", "mM9{E", "mM9{E", "lgz.3w0I0vAKj 'Cj", 2879, false, false, "");
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("", "", "", premiumTop0, "", 1121.803067934622, linkedList0);
      album0.next(user0);
      album0.addSong("H~;9Jh#Ri9s_*D9~[ ", "", "", "Album{title='', artist='', releaseYear=0, genre='', songs=[Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}], currentSong=Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}}", "Album{title='', artist='', releaseYear=0, genre='', songs=[Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}], currentSong=Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}}", 3485, false, true, "");
      // Undeclared exception!
      album0.nextShuffle();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("mM9{E", "mM9{E", "mM9{E", "mM9{E", "lgz.3w0I0vAKj 'Cj", 2879, false, false, "");
      album0.nextShuffle();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      User user1 = user0.clone();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      album0.addSong(", videolink='", "Ae>2_*_?UjI", ", durationinseconds=", "", "0qt!h6\" !V", 1, false, true, ", genre='");
      album0.addSong("0gT=|/4qRC0p6w{_89", "0gT=|/4qRC0p6w{_89", "X7aV|<_Lf[Y-O%HXYP~", "0gT=|/4qRC0p6w{_89", "0gT=|/4qRC0p6w{_89", 31, true, false, "");
      album0.nextShuffle();
      album0.previous(user0);
      album0.next(user1);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      album0.addSong(", durationinseconds=", "TQAAupC:>~&sL", "Zpvu94+{$8SY=$P", "h~;9jh#ri9s_*d9~[ ", "Y^-kCazs.Q-REtxk<-)", 162, false, false, "h~;9jh#ri9s_*d9~[ ");
      album0.next(user0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Album album0 = new Album();
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("", "", "", premiumTop0, "", 1121.803067934622, linkedList0);
      // Undeclared exception!
      try { 
        album0.next(user0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("mM9{E", "mM9{E", "mM9{E", "mM9{E", "lgz.3w0I0vAKj 'Cj", 2879, false, false, "");
      // Undeclared exception!
      try { 
        album0.addSong("mM9{E", "", "", "Album{title='', artist='', releaseYear=0, genre='', songs=[Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}], currentSong=Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}}", "Album{title='', artist='', releaseYear=0, genre='', songs=[Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}], currentSong=Song{name='mM9{E', artist='', publisher='mM9{E', lyrics='mM9{E', musicalNotes='mM9{E', genre='lgz.3w0I0vAKj 'Cj', durationInSeconds=2879, timesPlayed=0}}", 3485, false, true, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A song with the same name already exists in the album.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong("pC'qjK", "ph", "pC'qjK", ":", ", email='", 0, false, false, "ph");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song duration must be positive.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong("", "0gT=|/4qRC0p6w{_89", (String) null, (String) null, "X7aV|<_Lf[Y-O%HXYP~", 0, true, true, "0gt=|/4qrc0p6w{_89");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song name cannot be null or empty.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong((String) null, (String) null, "\u0000U)PF\"{B1Wf9|\"N8)", "Song name cannot be null or empty.", "", 1, false, true, "\u0000U)PF\"{B1Wf9|\"N8)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song name cannot be null or empty.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("xq!gqK2v{c9S_L(", "h~;9jh#ri9s_*d9~3[ ", 966, "xq!gqK2v{c9S_L(", linkedList0);
      album0.addSong(", durationInSeconds=", "h~;9jh#ri9s_*d9~3[ ", ", durationInSeconds=", ", lyrics='", ",nreleaseYear=", 31, false, false, "h~;9jh#ri9s_*d9~[ ");
      Album album1 = album0.clone();
      assertEquals("xq!gqK2v{c9S_L(", album1.getTitle());
      assertEquals(966, album0.getReleaseYear());
      assertEquals("h~;9jh#ri9s_*d9~3[ ", album1.getArtist());
      assertEquals(0, linkedList0.size());
      assertEquals(966, album1.getReleaseYear());
      assertEquals("xq!gqK2v{c9S_L(", album1.getGenre());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Album album0 = new Album();
      Song song0 = new Song();
      album0.setCurrentSong(song0);
      song0.setTimesPlayed((-117));
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.setCurrentSong();
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      album0.play(user0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Album album0 = new Album();
      album0.setArtist("org.spotifumtp37.model.user.History");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Album album0 = new Album();
      album0.deleteSong("Album{title='', artist='org.spotifumtp37.model.user.History', releaseYear=642, genre='', songs=[], currentSong=Song{name='', artist='', publisher='', lyrics='', musicalNotes='', genre='', durationInSeconds=0, timesPlayed=0}}");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Album album0 = new Album();
      album0.setGenre("zwPXrynDfIsdLaV");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.toString();
      assertEquals("Album{title='', artist='', releaseYear=0, genre='', songs=[], currentSong=Song{name='', artist='', publisher='', lyrics='', musicalNotes='', genre='', durationInSeconds=0, timesPlayed=0}}", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = album0.clone();
      assertEquals(0, album1.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Album album0 = new Album();
      album0.getTotalDuration();
      assertEquals(0, album0.getReleaseYear());
  }
}
