/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:36:22 GMT 2026
 */

package org.spotifumtp37.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.spotifumtp37.exceptions.SubscriptionDoesNotAllowException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubscriptionDoesNotAllowException_ESTest extends SubscriptionDoesNotAllowException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubscriptionDoesNotAllowException subscriptionDoesNotAllowException0 = new SubscriptionDoesNotAllowException("");
  }
}
