/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 13:03:04 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistFavorites;
import org.Model.Playlist.PlaylistRandom;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlaylistFavorites_ESTest extends PlaylistFavorites_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      playlistFavorites0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlistFavorites0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(linkedList0);
      PlaylistFavorites playlistFavorites1 = new PlaylistFavorites();
      playlistFavorites0.setName((String) null);
      // Undeclared exception!
      try { 
        playlistFavorites0.equals(playlistFavorites1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Playlist playlist0 = new Playlist((String) null, "net.jqwik.api.providers.TypeUsage$TypeUsageFacade");
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(playlist0);
      playlistFavorites0.setId((-4006));
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      assertEquals((-4006), playlistRandom0.getId());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(linkedList0);
      PlaylistFavorites playlistFavorites1 = new PlaylistFavorites();
      boolean boolean0 = playlistFavorites0.equals(playlistFavorites1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(linkedList0);
      boolean boolean0 = playlistFavorites0.equals(playlistFavorites0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      Music music0 = new Music("", "", "", "nome='", "nome='", "Duplicate registration of handler for ", "Duplicate registration of handler for ", (-2265), false);
      boolean boolean0 = playlistFavorites0.equals(music0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      assertEquals("", playlistRandom0.getAutor());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      List<Music> list0 = playlistFavorites0.getMusics();
      PlaylistFavorites playlistFavorites1 = new PlaylistFavorites(list0);
      PlaylistRandom playlistRandom0 = playlistFavorites1.clone();
      assertEquals("SpotifyUM", playlistRandom0.getAutor());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      String string0 = playlistFavorites0.toString();
      assertEquals("Playlist Favoritos{nome='', autor='', musicas=[]}", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = null;
      try {
        playlistFavorites0 = new PlaylistFavorites((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }
}
