/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri May 08 18:49:02 GMT 2026
 */

package org.Model.Music;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MusicReproduction_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.Model.Music.MusicReproduction"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/gongas/Desktop/3ano2sem/ATS_Aulas/ATS/SpotifyUM_Maven"); 
    java.lang.System.setProperty("user.home", "/home/gongas"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "gongas"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MusicReproduction_ESTest_scaffolding.class.getClassLoader() ,
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.jqwik.api.GenerationMode",
      "net.jqwik.api.lifecycle.ParameterResolutionContext",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.jqwik.engine.support.TypeResolution",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "net.bytebuddy.implementation.Implementation",
      "net.jqwik.engine.execution.DefaultParameterInjectionContext",
      "net.bytebuddy.description.ByteCodeElement",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "net.jqwik.api.lifecycle.PropagationMode",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.build.Plugin",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.implementation.EqualsMethod",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "net.jqwik.api.EdgeCasesMode",
      "net.jqwik.api.providers.TypeUsage",
      "net.bytebuddy.description.TypeVariableSource",
      "net.jqwik.engine.support.MethodParameter",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "net.jqwik.api.FixedSeedMode",
      "org.apiguardian.api.API",
      "org.apiguardian.api.API$Status",
      "net.jqwik.api.AfterFailureMode",
      "net.jqwik.api.ShrinkingMode",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.matcher.ElementMatcher",
      "net.bytebuddy.build.Plugin$Factory",
      "net.bytebuddy.description.type.TypeDefinition",
      "net.bytebuddy.implementation.HashCodeMethod",
      "org.Model.Music.MusicReproduction",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.Model.Music.Music",
      "net.bytebuddy.description.type.TypeDescription",
      "net.bytebuddy.description.NamedElement"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MusicReproduction_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.Model.Music.MusicReproduction",
      "org.apiguardian.api.API$Status",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.jqwik.api.EdgeCasesMode",
      "net.jqwik.api.FixedSeedMode",
      "net.jqwik.api.AfterFailureMode",
      "net.jqwik.api.ShrinkingMode",
      "net.jqwik.api.GenerationMode",
      "net.jqwik.api.lifecycle.PropagationMode",
      "org.Model.Music.Music",
      "net.jqwik.engine.support.MethodParameter",
      "net.jqwik.engine.execution.DefaultParameterInjectionContext",
      "net.jqwik.engine.support.TypeResolution"
    );
  }
}
