/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 13:12:52 GMT 2026
 */

package org.Exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.Exceptions.NoPremissionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoPremissionException_ESTest extends NoPremissionException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoPremissionException noPremissionException0 = new NoPremissionException("");
      String string0 = noPremissionException0.getMessage();
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", string0);
  }
}
