/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 21:38:44 GMT 2026
 */

package org.spotifumtp37.delegate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.nio.CharBuffer;
import java.nio.channels.DatagramChannel;
import java.nio.channels.SocketChannel;
import java.nio.file.Path;
import java.util.Enumeration;
import java.util.NoSuchElementException;
import java.util.Scanner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.spotifumtp37.delegate.AdminUI;
import org.spotifumtp37.model.SpotifUMData;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AdminUI_ESTest extends AdminUI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("n?o {xQ4^X");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.saveData();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.loadFromJson("");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.handleTopListenerFromDate();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Scanner scanner0 = new Scanner("org.spotifumtp37.model.subscription.PremiumBase");
      AdminUI adminUI0 = new AdminUI((SpotifUMData) null, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.viewAllPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("d!~MemY<k8[6(>\"LY6^");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.deserializeData();
      // Undeclared exception!
      try { 
        adminUI0.serializeData();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.serializeData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      scanner0.close();
      // Undeclared exception!
      try { 
        adminUI0.serializeData();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      SocketChannel socketChannel0 = SocketChannel.open();
      Scanner scanner0 = new Scanner(socketChannel0);
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.saveToJson((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("albums.json");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      try { 
        adminUI0.saveToJson("");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Enumeration<InputStream> enumeration0 = (Enumeration<InputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      Scanner scanner0 = new Scanner(sequenceInputStream0);
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.saveData();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.saveData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      scanner0.close();
      // Undeclared exception!
      try { 
        adminUI0.saveData();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      MockFile mockFile0 = new MockFile("");
      Path path0 = mockFile0.toPath();
      Scanner scanner0 = new Scanner(path0);
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.loadData();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      DatagramChannel.open();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.loadData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      scanner0.close();
      // Undeclared exception!
      try { 
        adminUI0.loadData();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.handleTopListenerFromDate();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Random.setNextRandom(653);
      SpotifUMData spotifUMData0 = new SpotifUMData();
      DatagramChannel.open();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.handleTopListenerFromDate();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.deserializeData();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.deserializeData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      scanner0.close();
      // Undeclared exception!
      try { 
        adminUI0.deserializeData();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.deleteUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Scanner scanner0 = new Scanner("");
      scanner0.close();
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.deleteUser();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(byteArrayInputStream0, byteArrayInputStream0);
      Scanner scanner0 = new Scanner(sequenceInputStream0);
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.deletePlaylistAdmin();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.deletePlaylistAdmin();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      AdminUI adminUI0 = new AdminUI((SpotifUMData) null, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.deleteAlbum();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Scanner scanner0 = new Scanner("SF~uK(1bW$+-u");
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.createPlaylistAdmin();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.createPlaylistAdmin();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      scanner0.close();
      // Undeclared exception!
      try { 
        adminUI0.createPlaylistAdmin();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.createAlbum();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Scanner scanner0 = new Scanner("");
      scanner0.close();
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.createAlbum();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      AdminUI adminUI0 = new AdminUI((SpotifUMData) null, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.clearSystemData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.delegate.AdminUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      try { 
        adminUI0.loadFromJson("Operation cancelled.");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("M&DK=ezV ?`=xUl'(");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.deleteUser();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.viewAllUsers();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.viewAllPlaylists();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("SF~uK(1bW$+-u");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.viewAllAlbums();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("User With Most Points: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.deleteAlbum();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("SF~uK(1bW$+-u");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.createAlbum();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("EG");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.serializeData();
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      char[] charArray0 = new char[8];
      charArray0[0] = 'W';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      Scanner scanner0 = new Scanner(charBuffer0);
      AdminUI adminUI0 = new AdminUI((SpotifUMData) null, scanner0);
      adminUI0.serializeData();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.showPlaylistManagementMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.showUserManagementMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("gI`I#a+c$2UGg=");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.printCurrentData();
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      AdminUI adminUI0 = new AdminUI((SpotifUMData) null, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.showAdminMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.saveToJson("");
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      AdminUI adminUI0 = new AdminUI(spotifUMData0, (Scanner) null);
      // Undeclared exception!
      try { 
        adminUI0.showDataMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("gI`I#a+c$2UGg=");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.showAlbumManagementMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      // Undeclared exception!
      try { 
        adminUI0.showStatisticsMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("The song's genre: ");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.clearSystemData();
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Scanner scanner0 = new Scanner("gI`I#a+c$2UGg=");
      AdminUI adminUI0 = new AdminUI(spotifUMData0, scanner0);
      adminUI0.loadData();
  }
}
